// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
	"github.com/grindlemire/go-tui/internal/debug"
)

func increment(count *tui.State[int]) func(*tui.Element) {
	return func(el *tui.Element) {
		debug.Log("increment callback called")
		count.Set(count.Get() + 1)
	}
}

func decrement(count *tui.State[int]) func(*tui.Element) {
	return func(el *tui.Element) {
		count.Set(count.Get() - 1)
	}
}

func handleKeys(count *tui.State[int]) func(*tui.Element, tui.KeyEvent) {
	return func(el *tui.Element, e tui.KeyEvent) {
		debug.Log("[CounterUI] handleKeys called: %+v", e)
		switch e.Rune {
		case '+':
			count.Set(count.Get() + 1)
		case '-':
			count.Set(count.Get() - 1)
		}
	}
}

func tick(count *tui.State[int]) func() {
	return func() {
		debug.Log("tick callback called")
		count.Set(count.Get() + 1)
	}
}

type CounterUIView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v CounterUIView) GetRoot() tui.Renderable { return v.Root }

func (v CounterUIView) GetWatchers() []tui.Watcher { return v.watchers }

func CounterUI() CounterUIView {
	var view CounterUIView
	var watchers []tui.Watcher

	count := tui.NewState(0)
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithOnKeyPress(handleKeys(count)),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_2 := tui.New(
		tui.WithText("Reactive Counter"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("Count:"),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(fmt.Sprintf("%d", count.Get())),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Blue)),
	)
	__tui_1.AddChild(__tui_5)
	__tui_0.AddChild(__tui_1)
	__tui_6 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_8 := tui.New(
		tui.WithOnClick(increment(count)),
	)
	__tui_9 := tui.New(tui.WithText(" + "))
	__tui_8.AddChild(__tui_9)
	__tui_7.AddChild(__tui_8)
	__tui_10 := tui.New(
		tui.WithOnClick(decrement(count)),
	)
	__tui_11 := tui.New(tui.WithText(" - "))
	__tui_10.AddChild(__tui_11)
	__tui_7.AddChild(__tui_10)
	__tui_0.AddChild(__tui_7)
	__tui_12 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_13 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_12.AddChild(__tui_13)
	__tui_0.AddChild(__tui_12)

	// Attach watchers (deferred until refs are assigned)
	__tui_0.AddWatcher(tui.OnTimer(time.Second, tick(count)))

	// State bindings
	count.Bind(func(_ int) {
		__tui_5.SetText(fmt.Sprintf("%d", count.Get()))
	})

	view = CounterUIView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
