// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
	"github.com/grindlemire/go-tui/internal/debug"
)

type counterApp struct {
	count        *tui.State[int]
	incrementBtn *tui.Ref
	decrementBtn *tui.Ref
}

func Counter() *counterApp {
	return &counterApp{
		count:        tui.NewState(0),
		incrementBtn: tui.NewRef(),
		decrementBtn: tui.NewRef(),
	}
}

func (c *counterApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnRune('+', func(ke tui.KeyEvent) {
			debug.Log("increment via KeyMap")
			c.count.Set(c.count.Get() + 1)
		}),
		tui.OnRune('-', func(ke tui.KeyEvent) {
			c.count.Set(c.count.Get() - 1)
		}),
	}
}

func (c *counterApp) HandleMouse(me tui.MouseEvent) bool {
	if me.Button == tui.MouseLeft && me.Action == tui.MousePress {
		if c.incrementBtn.El() != nil && c.incrementBtn.El().ContainsPoint(me.X, me.Y) {
			debug.Log("increment via HandleMouse")
			c.count.Set(c.count.Get() + 1)
			return true
		}
		if c.decrementBtn.El() != nil && c.decrementBtn.El().ContainsPoint(me.X, me.Y) {
			c.count.Set(c.count.Get() - 1)
			return true
		}
	}
	return false
}

func (c *counterApp) tick() {
	debug.Log("tick callback called")
	c.count.Set(c.count.Get() + 1)
}

func (c *counterApp) Render(app *tui.App) *tui.Element {
	incrementBtn := c.incrementBtn
	decrementBtn := c.decrementBtn
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_2 := tui.New(
		tui.WithText("Reactive Counter"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("Count:"),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(fmt.Sprintf("%d", c.count.Get())),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Blue)),
	)
	__tui_1.AddChild(__tui_5)
	__tui_0.AddChild(__tui_1)
	__tui_6 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_8 := tui.New()
	incrementBtn.Set(__tui_8)
	__tui_9 := tui.New(tui.WithText(" + "))
	__tui_8.AddChild(__tui_9)
	__tui_7.AddChild(__tui_8)
	__tui_10 := tui.New()
	decrementBtn.Set(__tui_10)
	__tui_11 := tui.New(tui.WithText(" - "))
	__tui_10.AddChild(__tui_11)
	__tui_7.AddChild(__tui_10)
	__tui_0.AddChild(__tui_7)
	__tui_12 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_13 := tui.New(
		tui.WithText("Press +/- or q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_12.AddChild(__tui_13)
	__tui_0.AddChild(__tui_12)

	// Attach watchers (deferred until refs are assigned)
	__tui_0.AddWatcher(tui.OnTimer(time.Second, c.tick))

	return __tui_0
}
