// Code generated by tui generate. DO NOT EDIT.
// Source: search.gsx

package main

import (
	"fmt"
	"strings"

	tui "github.com/grindlemire/go-tui"
)

type searchBar struct {
	active *tui.State[bool]
	query  *tui.State[string]
}

type content struct {
	category    *tui.State[string]
	categoryBus *tui.Events[string]
	query       *tui.State[string]
}

var filesByCategory = map[string][]string{
	"Documents": {"report.pdf", "notes.md", "budget.xlsx", "readme.txt", "design.doc"},
	"Images":    {"photo.jpg", "screenshot.png", "logo.svg", "banner.gif", "icon.ico"},
	"Music":     {"song.mp3", "album.flac", "podcast.ogg", "ringtone.wav"},
	"Projects":  {"go-tui/", "website/", "api-server/", "mobile-app/", "scripts/"},
	"Downloads": {"setup.exe", "archive.zip", "data.csv", "patch-v2.tar.gz"},
}

func SearchBar(active *tui.State[bool], query *tui.State[string]) *searchBar {
	return &searchBar{active: active, query: query}
}

func (s *searchBar) KeyMap() tui.KeyMap {
	if !s.active.Get() {
		return nil
	}
	return tui.KeyMap{
		tui.OnRunesStop(s.appendChar),
		tui.OnKeyStop(tui.KeyBackspace, s.deleteChar),
		tui.OnKeyStop(tui.KeyEnter, s.submit),
		tui.OnKeyStop(tui.KeyEscape, s.deactivate),
	}
}

func (s *searchBar) appendChar(ke tui.KeyEvent) {
	s.query.Set(s.query.Get() + string(ke.Rune))
}

func (s *searchBar) deleteChar(ke tui.KeyEvent) {
	q := s.query.Get()
	if len(q) > 0 {
		s.query.Set(q[:len(q)-1])
	}
}

func (s *searchBar) submit(ke tui.KeyEvent) {
	s.active.Set(false)
}

func (s *searchBar) deactivate(ke tui.KeyEvent) {
	s.active.Set(false)
	s.query.Set("")
}

func Content(query *tui.State[string]) *content {
	c := &content{
		category:    tui.NewState("Documents"),
		categoryBus: tui.NewEvents[string](categoryTopic),
		query:       query,
	}
	c.categoryBus.Subscribe(c.onCategoryChanged)
	return c
}

func (c *content) onCategoryChanged(category string) {
	c.category.Set(category)
}

func (c *content) filteredFiles() []string {
	cat := c.category.Get()
	files, ok := filesByCategory[cat]
	if !ok {
		return nil
	}
	q := strings.ToLower(c.query.Get())
	if q == "" {
		return files
	}
	var result []string
	for _, f := range files {
		if strings.Contains(strings.ToLower(f), q) {
			result = append(result, f)
		}
	}
	return result
}

func (s *searchBar) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithFlexShrink(0),
	)
	if s.active.Get() {
		__tui_1 := tui.New(
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
			tui.WithPadding(1),
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_2 := tui.New(
			tui.WithText("Search:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(s.query.Get()),
		)
		__tui_1.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_1.AddChild(__tui_4)
		__tui_0.AddChild(__tui_1)
	}

	return __tui_0
}

func (s *searchBar) BindApp(app *tui.App) {
	if s.active != nil {
		s.active.BindApp(app)
	}
	if s.query != nil {
		s.query.BindApp(app)
	}
}

var _ tui.AppBinder = (*searchBar)(nil)

func (c *content) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText(c.category.Get()+"/"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	for i, file := range c.filteredFiles() {
		_ = i
		if i == len(c.filteredFiles())-1 {
			__tui_3 := tui.New(
				tui.WithText(fmt.Sprintf("  └── %s", file)),
			)
			__tui_0.AddChild(__tui_3)
		} else {
			__tui_4 := tui.New(
				tui.WithText(fmt.Sprintf("  ├── %s", file)),
			)
			__tui_0.AddChild(__tui_4)
		}
	}
	if len(c.filteredFiles()) == 0 {
		__tui_5 := tui.New(
			tui.WithText("No matching files"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_5)
	}
	if c.query.Get() != "" {
		__tui_6 := tui.New(
			tui.WithWidth(0),
			tui.WithHeight(1),
		)
		__tui_0.AddChild(__tui_6)
		__tui_7 := tui.New(
			tui.WithText(fmt.Sprintf("Filtering: \"%s\"", c.query.Get())),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_7)
	}

	return __tui_0
}

func (c *content) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*content)
	if !ok {
		return
	}
	c.categoryBus = f.categoryBus
}

var _ tui.PropsUpdater = (*content)(nil)

func (c *content) BindApp(app *tui.App) {
	if c.category != nil {
		c.category.BindApp(app)
	}
	if c.categoryBus != nil {
		c.categoryBus.BindApp(app)
	}
	if c.query != nil {
		c.query.BindApp(app)
	}
}

var _ tui.AppBinder = (*content)(nil)

func (c *content) UnbindApp() {
	if c.categoryBus != nil {
		c.categoryBus.UnbindApp()
	}
}

var _ tui.AppUnbinder = (*content)(nil)
