// Code generated by tui generate. DO NOT EDIT.
// Source: counter.tui

package main

import (
	"fmt"
	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func CounterUI(count int) *element.Element {
	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(2),
	)
	__tui_1 := element.New(
		element.WithBorder(tui.BorderRounded),
		element.WithPadding(1),
		element.WithDirection(layout.Column),
		element.WithAlign(layout.AlignCenter),
		element.WithJustify(layout.JustifyCenter),
	)
	__tui_2 := element.New(
		element.WithText("Counter Example"),
		element.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := element.New(
		element.WithText("Count:"),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := element.New(
		element.WithText(fmt.Sprintf("%d", count)),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_4)
	__tui_0.AddChild(__tui_1)
	__tui_5 := element.New(
		element.WithDirection(layout.Row),
		element.WithGap(1),
		element.WithJustify(layout.JustifyCenter),
	)
	__tui_6 := element.New(
		element.WithText("Press +/- to change, q to quit"),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_5.AddChild(__tui_6)
	__tui_0.AddChild(__tui_5)
	return __tui_0
}
