// Code generated by tui generate. DO NOT EDIT.
// Source: refs.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

func itemStyle(idx, selected int) string {
	if idx == selected {
		return "font-bold text-cyan"
	}
	return "text-white"
}

type RefsDemoView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	Header    *tui.Element
	Content   *tui.Element
	ItemRefs  []*tui.Element
	Warning   *tui.Element // may be nil
	StatusBar *tui.Element
}

func (v RefsDemoView) GetRoot() tui.Renderable { return v.Root }

func (v RefsDemoView) GetWatchers() []tui.Watcher { return v.watchers }

func RefsDemo(items []string, showWarning bool, selectedIdx int) RefsDemoView {
	var view RefsDemoView
	var watchers []tui.Watcher

	header := tui.NewRef()
	content := tui.NewRef()
	itemRefs := tui.NewRefList()
	warning := tui.NewRef()
	statusBar := tui.NewRef()
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithHeight(24),
		tui.WithWidth(80),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	header.Set(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("Named Element Refs Demo"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithDirection(tui.Column),
	)
	content.Set(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("Items (loop refs) - j/k to scroll, +/- to select"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	__tui_3.AddChild(__tui_4)
	for i, item := range items {
		_ = i
		__tui_5 := tui.New(
			tui.WithText(item),
		)
		itemRefs.Append(__tui_5)
		__tui_3.AddChild(__tui_5)
	}
	__tui_0.AddChild(__tui_3)
	if showWarning {
		__tui_6 := tui.New(
			tui.WithBorder(tui.BorderDouble),
			tui.WithPadding(1),
			tui.WithHeight(3),
			tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifyCenter),
			tui.WithAlign(tui.AlignCenter),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		warning.Set(__tui_6)
		__tui_7 := tui.New(
			tui.WithText("⚠ Warning: This is a conditional ref (may be nil)"),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_6.AddChild(__tui_7)
		__tui_0.AddChild(__tui_6)
	}
	__tui_8 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithAlign(tui.AlignCenter),
	)
	statusBar.Set(__tui_8)
	__tui_9 := tui.New(
		tui.WithText("j/k: scroll | +/-: select | Tab: warning | d: switch demo | q: quit"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_8.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText(fmt.Sprintf(" Selected: %d", selectedIdx)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_8.AddChild(__tui_10)
	__tui_0.AddChild(__tui_8)

	view = RefsDemoView{
		Root:      __tui_0,
		watchers:  watchers,
		Header:    header.El(),
		Content:   content.El(),
		ItemRefs:  itemRefs.All(),
		Warning:   warning.El(),
		StatusBar: statusBar.El(),
	}
	return view
}

type KeyedRefsDemoView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	UserRefs []*tui.Element
}

func (v KeyedRefsDemoView) GetRoot() tui.Renderable { return v.Root }

func (v KeyedRefsDemoView) GetWatchers() []tui.Watcher { return v.watchers }

func KeyedRefsDemo(users []User) KeyedRefsDemoView {
	var view KeyedRefsDemoView
	var watchers []tui.Watcher

	userRefs := tui.NewRefList()
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithHeight(20),
		tui.WithWidth(60),
	)
	__tui_1 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_2 := tui.New(
		tui.WithText("Keyed Refs Demo (map access)"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithFlexGrow(1),
	)
	__tui_4 := tui.New(
		tui.WithText("Users (keyed by ID)"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	__tui_3.AddChild(__tui_4)
	for __idx_0, user := range users {
		_ = __idx_0
		__tui_5 := tui.New(
			tui.WithText(fmt.Sprintf("[%s] %s", user.ID, user.Name)),
		)
		userRefs.Append(__tui_5)
		__tui_3.AddChild(__tui_5)
	}
	__tui_0.AddChild(__tui_3)
	__tui_6 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithHeight(2),
	)
	__tui_7 := tui.New(
		tui.WithText("1-3: highlight user | d: switch demo | q: quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_6.AddChild(__tui_7)
	__tui_0.AddChild(__tui_6)

	view = KeyedRefsDemoView{
		Root:     __tui_0,
		watchers: watchers,
		UserRefs: userRefs.All(),
	}
	return view
}
