// Code generated by tui generate. DO NOT EDIT.
// Source: state.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type demoApp struct {
	count    *tui.State[int]
	selected *tui.State[int]
	items    []string
}

func Demo() *demoApp {
	return &demoApp{
		count:    tui.NewState(0),
		selected: tui.NewState(0),
		items:    []string{"Rust", "Go", "TypeScript", "Python", "Zig"},
	}
}

func (d *demoApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('+', func(ke tui.KeyEvent) {
			d.count.Update(func(v int) int { return v + 1 })
		}),
		tui.OnRune('-', func(ke tui.KeyEvent) {
			d.count.Update(func(v int) int { return v - 1 })
		}),
		tui.OnRune('r', func(ke tui.KeyEvent) {
			ke.App().Batch(func() {
				d.count.Set(0)
				d.selected.Set(0)
			})
		}),
		tui.OnRune('j', func(ke tui.KeyEvent) { d.selectNext() }),
		tui.OnRune('k', func(ke tui.KeyEvent) { d.selectPrev() }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { d.selectNext() }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { d.selectPrev() }),
	}
}

func (d *demoApp) selectNext() {
	d.selected.Update(func(v int) int {
		if v >= len(d.items)-1 {
			return 0
		}
		return v + 1
	})
}

func (d *demoApp) selectPrev() {
	d.selected.Update(func(v int) int {
		if v <= 0 {
			return len(d.items) - 1
		}
		return v - 1
	})
}

func signLabel(n int) string {
	if n > 0 {
		return "Positive"
	}
	if n < 0 {
		return "Negative"
	}
	return "Zero"
}

func signClass(n int) string {
	if n > 0 {
		return "text-green font-bold"
	}
	if n < 0 {
		return "text-red font-bold"
	}
	return "text-blue font-bold"
}

func (d *demoApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithText("State Demo"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
	)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFlexGrow(1.0),
	)
	__tui_4 := tui.New(
		tui.WithText("Counter"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(fmt.Sprintf("%d", d.count.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_3.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_7 := tui.New(
		tui.WithText("+/-r: reset"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_6.AddChild(__tui_7)
	__tui_3.AddChild(__tui_6)
	__tui_2.AddChild(__tui_3)
	__tui_8 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(2.0),
	)
	__tui_9 := tui.New(
		tui.WithText("Status"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_8.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_11 := tui.New(
		tui.WithText("Sign:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText(signLabel(d.count.Get())),
	)
	__tui_10.AddChild(__tui_12)
	__tui_8.AddChild(__tui_10)
	__tui_13 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_14 := tui.New(
		tui.WithText("Parity:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_13.AddChild(__tui_14)
	if d.count.Get()%2 == 0 {
		__tui_15 := tui.New(
			tui.WithText("Even"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_13.AddChild(__tui_15)
	} else {
		__tui_16 := tui.New(
			tui.WithText("Odd"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
		)
		__tui_13.AddChild(__tui_16)
	}
	__tui_8.AddChild(__tui_13)
	__tui_2.AddChild(__tui_8)
	__tui_0.AddChild(__tui_2)
	__tui_17 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_18 := tui.New(
		tui.WithText("Languages"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_17.AddChild(__tui_18)
	for i, item := range d.items {
		_ = i
		if i == d.selected.Get() {
			__tui_19 := tui.New(
				tui.WithText(fmt.Sprintf("  > %s", item)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_17.AddChild(__tui_19)
		} else {
			__tui_20 := tui.New(
				tui.WithText(fmt.Sprintf("    %s", item)),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_17.AddChild(__tui_20)
		}
	}
	__tui_0.AddChild(__tui_17)
	__tui_21 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_22 := tui.New(
		tui.WithText("+/-count|j/k navigate|r reset|esc quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_21.AddChild(__tui_22)
	__tui_0.AddChild(__tui_21)

	return __tui_0
}

func (d *demoApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*demoApp)
	if !ok {
		return
	}
	d.items = f.items
}

var _ tui.PropsUpdater = (*demoApp)(nil)

func (d *demoApp) BindApp(app *tui.App) {
	if d.count != nil {
		d.count.BindApp(app)
	}
	if d.selected != nil {
		d.selected.BindApp(app)
	}
}

var _ tui.AppBinder = (*demoApp)(nil)
