// Code generated by tui generate. DO NOT EDIT.
// Source: tree.gsx

package main

import (
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	tui "github.com/grindlemire/go-tui"
)

type Node struct {
	Name     string
	Children []Node
}

type visibleNode struct {
	node      Node
	depth     int
	path      string
	isDir     bool
	isLast    bool
	ancestors []bool
	onPath    bool
}

type directoryTree struct {
	rootPath        string
	tree            []Node
	cursor          *tui.State[int]
	expanded        *tui.State[map[string]bool]
	scrollY         *tui.State[int]
	scrollContainer *tui.Ref
}

func DirectoryTree(root string) *directoryTree {
	rootNode := buildRootNode(root)
	return &directoryTree{
		rootPath:        root,
		tree:            []Node{rootNode},
		cursor:          tui.NewState(0),
		expanded:        tui.NewState(map[string]bool{rootNode.Name: true}),
		scrollY:         tui.NewState(0),
		scrollContainer: tui.NewRef(),
	}
}

func (d *directoryTree) navigateUp() {
	parent := filepath.Dir(d.rootPath)
	if parent == d.rootPath {
		return
	}
	d.rootPath = parent
	rootNode := buildRootNode(parent)
	d.tree = []Node{rootNode}
	d.cursor.Set(0)
	d.expanded.Set(map[string]bool{rootNode.Name: true})
	d.scrollY.Set(0)
}

func (d *directoryTree) visibleSelectedPath() string {
	visible := d.visibleNodes()
	cur := d.cursor.Get()
	if cur >= len(visible) {
		return ""
	}
	return visible[cur].path
}

func (d *directoryTree) loadChildren(nodePath string) {
	parts := strings.Split(nodePath, "/")
	node := &d.tree[0]
	fsPath := d.rootPath
	for _, part := range parts[1:] {
		found := false
		for i := range node.Children {
			if node.Children[i].Name == part {
				node = &node.Children[i]
				fsPath = filepath.Join(fsPath, part)
				found = true
				break
			}
		}
		if !found {
			return
		}
	}
	if len(node.Children) == 0 {
		node.Children = readDir(fsPath)
		if node.Children == nil {
			node.Children = []Node{}
		}
	}
}

func (d *directoryTree) scrollToCursor() {
	el := d.scrollContainer.El()
	if el == nil {
		return
	}
	cur := d.cursor.Get()
	_, vpH := el.ViewportSize()
	y := d.scrollY.Get()
	if cur < y {
		d.scrollY.Set(cur)
	} else if cur >= y+vpH {
		d.scrollY.Set(cur - vpH + 1)
	}
}

func (d *directoryTree) visibleNodes() []visibleNode {
	var result []visibleNode
	expanded := d.expanded.Get()
	for i, node := range d.tree {
		flattenNode(node, 0, node.Name, i == len(d.tree)-1, nil, expanded, &result)
	}
	cur := d.cursor.Get()
	if cur < len(result) {
		sel := result[cur].path
		for i := range result {
			result[i].onPath = result[i].path == sel || strings.HasPrefix(sel, result[i].path+"/")
		}
	}
	return result
}

func (d *directoryTree) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.OnChange(d.cursor, func(int) { d.scrollToCursor() }),
	}
}

func (d *directoryTree) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { d.moveUp() }),
		tui.OnRune('k', func(ke tui.KeyEvent) { d.moveUp() }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { d.moveDown() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { d.moveDown() }),
		tui.OnKey(tui.KeyEnter, func(ke tui.KeyEvent) { d.toggle() }),
		tui.OnKey(tui.KeyRight, func(ke tui.KeyEvent) { d.toggle() }),
		tui.OnRune('l', func(ke tui.KeyEvent) { d.toggle() }),
		tui.OnKey(tui.KeyLeft, func(ke tui.KeyEvent) { d.collapseOrParent() }),
		tui.OnRune('h', func(ke tui.KeyEvent) { d.collapseOrParent() }),
	}
}

func (d *directoryTree) moveUp() {
	d.cursor.Update(func(v int) int {
		if v > 0 {
			return v - 1
		}
		return v
	})
}

func (d *directoryTree) moveDown() {
	visible := d.visibleNodes()
	d.cursor.Update(func(v int) int {
		if v < len(visible)-1 {
			return v + 1
		}
		return v
	})
}

func (d *directoryTree) toggle() {
	visible := d.visibleNodes()
	cur := d.cursor.Get()
	if cur >= len(visible) {
		return
	}
	vn := visible[cur]
	if !vn.isDir {
		return
	}
	expanding := !d.expanded.Get()[vn.path]
	if expanding {
		d.loadChildren(vn.path)
	}
	d.expanded.Update(func(m map[string]bool) map[string]bool {
		return cloneExpandedWith(m, vn.path, expanding)
	})
}

func (d *directoryTree) collapseOrParent() {
	visible := d.visibleNodes()
	cur := d.cursor.Get()
	if cur >= len(visible) {
		return
	}
	vn := visible[cur]

	// If on an expanded directory, collapse it
	expanded := d.expanded.Get()
	if vn.isDir && expanded[vn.path] {
		d.expanded.Update(func(m map[string]bool) map[string]bool {
			return cloneExpandedWith(m, vn.path, false)
		})
		return
	}

	// At root, navigate to parent directory
	if vn.depth == 0 {
		d.navigateUp()
		return
	}

	// Jump to parent node
	parentPath := path.Dir(vn.path)
	for i := cur - 1; i >= 0; i-- {
		if visible[i].path == parentPath {
			d.cursor.Set(i)
			return
		}
	}
}

func readDir(dirPath string) []Node {
	entries, err := os.ReadDir(dirPath)
	if err != nil {
		return nil
	}

	var children []Node
	for _, entry := range entries {
		if entry.Name()[0] == '.' {
			continue
		}
		node := Node{Name: entry.Name()}
		if entry.IsDir() {
			node.Children = []Node{}
		}
		children = append(children, node)
	}
	sortChildren(children)
	return children
}

func sortChildren(children []Node) {
	sort.Slice(children, func(i, j int) bool {
		iDir := children[i].Children != nil
		jDir := children[j].Children != nil
		if iDir != jDir {
			return iDir
		}
		return children[i].Name < children[j].Name
	})
}

func buildRootNode(absPath string) Node {
	root := Node{
		Name:     filepath.Base(absPath),
		Children: readDir(absPath),
	}
	if root.Children == nil {
		root.Children = []Node{}
	}
	return root
}

func cloneExpandedWith(m map[string]bool, key string, val bool) map[string]bool {
	out := make(map[string]bool, len(m))
	for k, v := range m {
		out[k] = v
	}
	if val {
		out[key] = true
	} else {
		delete(out, key)
	}
	return out
}

func flattenNode(n Node, depth int, nodePath string, isLast bool, ancestors []bool, expanded map[string]bool, result *[]visibleNode) {
	isDir := n.Children != nil
	*result = append(*result, visibleNode{
		node:      n,
		depth:     depth,
		path:      nodePath,
		isDir:     isDir,
		isLast:    isLast,
		ancestors: ancestors,
	})
	if isDir && expanded[nodePath] {
		newAncestors := make([]bool, len(ancestors)+1)
		copy(newAncestors, ancestors)
		newAncestors[len(ancestors)] = isLast
		for i, child := range n.Children {
			childPath := nodePath + "/" + child.Name
			flattenNode(child, depth+1, childPath, i == len(n.Children)-1, newAncestors, expanded, result)
		}
	}
}

func buildPrefix(vn visibleNode) string {
	if vn.depth == 0 {
		return ""
	}
	var b strings.Builder
	for i := 0; i < vn.depth-1; i++ {
		if vn.ancestors[i+1] {
			b.WriteString("    ")
		} else {
			b.WriteString("│   ")
		}
	}
	if vn.isLast {
		b.WriteString("└── ")
	} else {
		b.WriteString("├── ")
	}
	return b.String()
}

func nodeLabel(vn visibleNode, expanded map[string]bool) string {
	if vn.isDir {
		if expanded[vn.path] {
			return "▼ " + vn.node.Name
		}
		return "▶ " + vn.node.Name
	}
	return vn.node.Name
}

func (d *directoryTree) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
	)
	__tui_2 := tui.New(
		tui.WithText("Directory Tree"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(d.visibleSelectedPath()),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollbarStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithScrollbarThumbStyle(tui.NewStyle().Foreground(tui.BrightCyan)),
		tui.WithScrollOffset(0, d.scrollY.Get()),
	)
	d.scrollContainer.Set(__tui_5)
	for i, vn := range d.visibleNodes() {
		_ = i
		if i == d.cursor.Get() {
			__tui_6 := tui.New(
				tui.WithText(buildPrefix(vn)+nodeLabel(vn, d.expanded.Get())),
				tui.WithBackground(tui.NewStyle().Background(tui.BrightBlack)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_5.AddChild(__tui_6)
		} else if vn.onPath {
			__tui_7 := tui.New(
				tui.WithText(buildPrefix(vn)+nodeLabel(vn, d.expanded.Get())),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_5.AddChild(__tui_7)
		} else if vn.isDir {
			__tui_8 := tui.New(
				tui.WithText(buildPrefix(vn)+nodeLabel(vn, d.expanded.Get())),
				tui.WithTextStyle(tui.NewStyle().Bold()),
			)
			__tui_5.AddChild(__tui_8)
		} else {
			__tui_9 := tui.New(
				tui.WithText(buildPrefix(vn) + nodeLabel(vn, d.expanded.Get())),
			)
			__tui_5.AddChild(__tui_9)
		}
	}
	__tui_0.AddChild(__tui_5)
	__tui_10 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithPadding(1),
	)
	__tui_12 := tui.New(
		tui.WithText("j/k: navigate | enter/l: expand | h: collapse | q: quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_12)
	__tui_0.AddChild(__tui_11)

	return __tui_0
}

func (d *directoryTree) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*directoryTree)
	if !ok {
		return
	}
	d.rootPath = f.rootPath
	d.tree = f.tree
}

var _ tui.PropsUpdater = (*directoryTree)(nil)

func (d *directoryTree) BindApp(app *tui.App) {
	if d.cursor != nil {
		d.cursor.BindApp(app)
	}
	if d.expanded != nil {
		d.expanded.BindApp(app)
	}
	if d.scrollY != nil {
		d.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*directoryTree)(nil)
