// Code generated by tui generate. DO NOT EDIT.
// Source: refs.gsx

package main

import (
	"fmt"

	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func handleIncrement(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() + 1)
	}
}

func handleDecrement(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() - 1)
	}
}

type RefsView struct {
	Root         *element.Element
	watchers     []tui.Watcher
	Counter      *element.Element
	IncrementBtn *element.Element
	DecrementBtn *element.Element
	Status       *element.Element
}

func (v RefsView) GetRoot() tui.Renderable { return v.Root }

func (v RefsView) GetWatchers() []tui.Watcher { return v.watchers }

func Refs() RefsView {
	var view RefsView
	var watchers []tui.Watcher

	var Counter *element.Element
	var IncrementBtn *element.Element
	var DecrementBtn *element.Element
	var Status *element.Element

	count := tui.NewState(0)
	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(2),
		element.WithBorder(tui.BorderRounded),
	)
	__tui_1 := element.New(
		element.WithText("Named Element References"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := element.New(
		element.WithHR(),
		element.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	Counter = element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
	)
	__tui_3 := element.New()
	__tui_4 := element.New(element.WithText("Counter"))
	__tui_3.AddChild(__tui_4)
	__tui_5 := element.New(element.WithText(fmt.Sprintf("%d", count.Get())))
	__tui_3.AddChild(__tui_5)
	Counter.AddChild(__tui_3)
	__tui_0.AddChild(Counter)
	__tui_6 := element.New(
		element.WithDirection(layout.Row),
		element.WithGap(1),
		element.WithWidthPercent(100.00),
		element.WithJustify(layout.JustifyCenter),
	)
	IncrementBtn = element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithTextAlign(element.TextAlignCenter),
		element.WithPadding(1),
		element.WithWidth(10),
		element.WithHeight(5),
	)
	__tui_7 := element.New(element.WithText(" + "))
	IncrementBtn.AddChild(__tui_7)
	__tui_6.AddChild(IncrementBtn)
	DecrementBtn = element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithTextAlign(element.TextAlignCenter),
		element.WithPadding(1),
		element.WithWidth(10),
		element.WithHeight(5),
	)
	__tui_8 := element.New(element.WithText(" - "))
	DecrementBtn.AddChild(__tui_8)
	__tui_6.AddChild(DecrementBtn)
	__tui_0.AddChild(__tui_6)
	Status = element.New(
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_9 := element.New(
		element.WithText("Click buttons to update the counter"),
	)
	Status.AddChild(__tui_9)
	__tui_0.AddChild(Status)
	__tui_10 := element.New(
		element.WithText("Press q to quit"),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)

	// Attach handlers (deferred until refs are assigned)
	IncrementBtn.SetOnClick(handleIncrement(count))
	DecrementBtn.SetOnClick(handleDecrement(count))

	// State bindings
	count.Bind(func(_ int) {
		__tui_5.SetText(fmt.Sprintf("%d", count.Get()))
	})

	view = RefsView{
		Root:         __tui_0,
		watchers:     watchers,
		Counter:      Counter,
		IncrementBtn: IncrementBtn,
		DecrementBtn: DecrementBtn,
		Status:       Status,
	}
	return view
}
