// Code generated by tui generate. DO NOT EDIT.
// Source: composition.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type compositionApp struct{}

func App() *compositionApp {
	return &compositionApp{}
}

func (a *compositionApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
	}
}

type CardView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v CardView) GetRoot() tui.Renderable { return v.Root }

func (v CardView) GetWatchers() []tui.Watcher { return v.watchers }

func Card(title string, children []*tui.Element) CardView {
	var view CardView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	for _, __child := range children {
		__tui_0.AddChild(__child)
	}

	view = CardView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}

type BadgeView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v BadgeView) GetRoot() tui.Renderable { return v.Root }

func (v BadgeView) GetWatchers() []tui.Watcher { return v.watchers }

func Badge(text string) BadgeView {
	var view BadgeView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithText(" "+text+" "),
		tui.WithBackgroundGradient(tui.NewGradient(tui.Blue, tui.Cyan).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White).Bold()),
	)

	view = BadgeView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}

type HeaderView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v HeaderView) GetRoot() tui.Renderable { return v.Root }

func (v HeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func Header(text string) HeaderView {
	var view HeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderDouble),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText(text),
		tui.WithTextGradient(tui.NewGradient(tui.Blue, tui.Cyan).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)

	view = HeaderView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}

type StatusLineView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v StatusLineView) GetRoot() tui.Renderable { return v.Root }

func (v StatusLineView) GetWatchers() []tui.Watcher { return v.watchers }

func StatusLine(label string, value string) StatusLineView {
	var view StatusLineView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText(label),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(value),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_2)

	view = StatusLineView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}

func (a *compositionApp) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_2 := tui.New(
		tui.WithText("Component Composition"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("Nested Components"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue).Bold()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_5 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1.0),
	)
	__tui_6 := tui.New(
		tui.WithText("@Component (leaf)"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_5.AddChild(__tui_6)
	__tui_7 := tui.Mount(a, 0, func() tui.Component {
		return Header("go-tui")
	})
	__tui_5.AddChild(__tui_7)
	__tui_8 := tui.Mount(a, 1, func() tui.Component {
		return Badge("Framework")
	})
	__tui_5.AddChild(__tui_8)
	__tui_4.AddChild(__tui_5)
	__tui_9 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1.0),
	)
	__tui_10 := tui.New(
		tui.WithText("@Component {children}"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_9.AddChild(__tui_10)
	__tui_11 := tui.Mount(a, 2, func() tui.Component {
		return Card("User Profile")
	})
	__tui_9.AddChild(__tui_11)
	__tui_4.AddChild(__tui_9)
	__tui_12 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1.0),
	)
	__tui_13 := tui.New(
		tui.WithText("Deep Nesting"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_12.AddChild(__tui_13)
	__tui_14 := tui.Mount(a, 3, func() tui.Component {
		return Card("Settings")
	})
	__tui_12.AddChild(__tui_14)
	__tui_4.AddChild(__tui_12)
	__tui_0.AddChild(__tui_4)
	__tui_15 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_16 := tui.New(
		tui.WithText("[q] quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_15.AddChild(__tui_16)
	__tui_0.AddChild(__tui_15)

	return __tui_0
}
