// Code generated by tui generate. DO NOT EDIT.
// Source: composition.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type compositionApp struct{}

func App() *compositionApp {
	return &compositionApp{}
}

func (a *compositionApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
	}
}

func (a *compositionApp) Render() *tui.Element {
	root := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithGap(1),
	)

	// Header row
	headerRow := tui.New(tui.WithDirection(tui.Row), tui.WithJustify(tui.JustifySpaceBetween))
	headerRow.AddChild(tui.New(
		tui.WithText("Component Composition"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	))
	headerRow.AddChild(tui.New(
		tui.WithText("Helper Functions"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue).Bold()),
	))
	root.AddChild(headerRow)

	// Main content row
	contentRow := tui.New(tui.WithDirection(tui.Row), tui.WithGap(1))

	// Column 1: Simple Helpers
	col1 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
	)
	col1.AddChild(tui.New(tui.WithText("Simple Helpers"), tui.WithTextStyle(tui.NewStyle().Bold())))
	col1.AddChild(Header("go-tui"))
	col1.AddChild(Badge("Framework"))
	contentRow.AddChild(col1)

	// Column 2: With Children
	col2 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
	)
	col2.AddChild(tui.New(tui.WithText("With Children"), tui.WithTextStyle(tui.NewStyle().Bold())))
	col2.AddChild(Card("User Profile",
		StatusLine("Name:", "Alice"),
		StatusLine("Role:", "Admin"),
		statusRow("Status:", Badge("Active")),
	))
	contentRow.AddChild(col2)

	// Column 3: Deep Nesting
	col3 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
	)
	col3.AddChild(tui.New(tui.WithText("Deep Nesting"), tui.WithTextStyle(tui.NewStyle().Bold())))
	col3.AddChild(Card("Settings",
		StatusLine("Theme:", "Dark"),
		StatusLine("Notify:", "On"),
		tagsRow(Badge("New"), Badge("v1.0")),
	))
	contentRow.AddChild(col3)

	root.AddChild(contentRow)

	// Footer
	footerRow := tui.New(tui.WithDirection(tui.Row), tui.WithJustify(tui.JustifyCenter))
	footerRow.AddChild(tui.New(tui.WithText("[q] quit"), tui.WithTextStyle(tui.NewStyle().Dim())))
	root.AddChild(footerRow)

	return root
}

func Card(title string, children ...*tui.Element) *tui.Element {
	card := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
	)
	card.AddChild(tui.New(
		tui.WithText(title),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	))
	card.AddChild(tui.New(tui.WithHR(), tui.WithBorder(tui.BorderSingle)))
	for _, child := range children {
		card.AddChild(child)
	}
	return card
}

func Badge(text string) *tui.Element {
	return tui.New(
		tui.WithText(" "+text+" "),
		tui.WithBackgroundGradient(tui.NewGradient(tui.Blue, tui.Cyan).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White).Bold()),
	)
}

func Header(text string) *tui.Element {
	header := tui.New(
		tui.WithBorder(tui.BorderDouble),
		tui.WithPadding(1),
	)
	header.AddChild(tui.New(
		tui.WithText(text),
		tui.WithTextGradient(tui.NewGradient(tui.Blue, tui.Cyan).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	))
	return header
}

func StatusLine(label string, value string) *tui.Element {
	line := tui.New(tui.WithDirection(tui.Row), tui.WithGap(1))
	line.AddChild(tui.New(tui.WithText(label), tui.WithTextStyle(tui.NewStyle().Dim())))
	line.AddChild(tui.New(tui.WithText(value), tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold())))
	return line
}

func statusRow(label string, badge *tui.Element) *tui.Element {
	row := tui.New(tui.WithDirection(tui.Row), tui.WithGap(1))
	row.AddChild(tui.New(tui.WithText(label), tui.WithTextStyle(tui.NewStyle().Dim())))
	row.AddChild(badge)
	return row
}

func tagsRow(badges ...*tui.Element) *tui.Element {
	row := tui.New(tui.WithDirection(tui.Row), tui.WithGap(1))
	row.AddChild(tui.New(tui.WithText("Tags:"), tui.WithTextStyle(tui.NewStyle().Dim())))
	for _, b := range badges {
		row.AddChild(b)
	}
	return row
}
