// Code generated by tui generate. DO NOT EDIT.
// Source: app.gsx

package main

import (
	"context"
	"time"

	tui "github.com/grindlemire/go-tui"
	"github.com/grindlemire/go-tui/examples/ai-chat/settings"
)

type chatApp struct {
	state        *AppState
	events       *tui.Events[ChatEvent]
	providers    map[string]Provider
	showHelp     *tui.State[bool]
	showSettings *tui.State[bool]
	tokenCh      chan string
	cancelFn     context.CancelFunc
}

func ChatApp(state *AppState, providers map[string]Provider) *chatApp {
	c := &chatApp{
		state:        state,
		events:       tui.NewEvents[ChatEvent](),
		providers:    providers,
		showHelp:     tui.NewState(false),
		showSettings: tui.NewState(false),
		tokenCh:      make(chan string, 100),
	}

	// Subscribe to events
	c.events.Subscribe(c.handleEvent)

	return c
}

func (c *chatApp) handleEvent(e ChatEvent) {
	switch e.Type {
	case "submit":
		c.sendMessage(e.Payload)
	case "cancel":
		if c.cancelFn != nil {
			c.cancelFn()
		}
	case "retry":
		c.retryLast()
	case "copy":
		// Clipboard not available in terminal - event ignored
	}
}

func (c *chatApp) sendMessage(content string) {
	if c.state.IsStreaming.Get() {
		return
	}

	// Add user message
	c.state.AddMessage(Message{
		Role:      "user",
		Content:   content,
		Timestamp: time.Now(),
	})

	// Start streaming response
	c.startStreaming()
}

func (c *chatApp) startStreaming() {
	provider, ok := c.providers[c.state.Provider.Get()]
	if !ok {
		c.state.Error.Set("Provider not available")
		return
	}

	c.state.IsStreaming.Set(true)
	c.state.Error.Set("")

	// Add placeholder assistant message
	c.state.AddMessage(Message{
		Role:      "assistant",
		Content:   "",
		Timestamp: time.Now(),
		Streaming: true,
	})

	ctx, cancel := context.WithCancel(context.Background())
	c.cancelFn = cancel

	tokenCh := make(chan string, 100)
	startTime := time.Now()

	go func() {
		msgs := c.state.Messages.Get()
		// Exclude the last (empty assistant) message
		chatMsgs := msgs[:len(msgs)-1]

		err := provider.Chat(ctx, chatMsgs, ChatOpts{
			Model:        c.state.Model.Get(),
			Temperature:  c.state.Temperature.Get(),
			SystemPrompt: c.state.SystemPrompt.Get(),
		}, tokenCh)

		if err != nil && err != context.Canceled {
			c.state.Error.Set(err.Error())
		}
	}()

	// Process tokens in a separate goroutine that sends to our channel
	go func() {
		var content string
		for token := range tokenCh {
			content += token
			c.tokenCh <- content
		}
		// Signal done
		duration := time.Since(startTime)
		c.tokenCh <- "DONE:" + content + "|" + duration.String()
	}()
}

func (c *chatApp) retryLast() {
	msgs := c.state.Messages.Get()
	if len(msgs) < 2 {
		return
	}
	// Remove last assistant message
	c.state.Messages.Set(msgs[:len(msgs)-1])
	c.startStreaming()
}

func (c *chatApp) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.Watch(c.tokenCh, c.handleToken),
	}
}

func (c *chatApp) handleToken(data string) {
	if len(data) > 5 && data[:5] == "DONE:" {
		// Parse done message
		rest := data[5:]
		// Find duration separator
		for i := len(rest) - 1; i >= 0; i-- {
			if rest[i] == '|' {
				content := rest[:i]
				durStr := rest[i+1:]
				dur, _ := time.ParseDuration(durStr)

				msgs := c.state.Messages.Get()
				if len(msgs) > 0 {
					msgs[len(msgs)-1].Content = content
					msgs[len(msgs)-1].Streaming = false
					msgs[len(msgs)-1].Duration = dur
					c.state.Messages.Set(msgs)
				}
				break
			}
		}
		c.state.IsStreaming.Set(false)
		c.cancelFn = nil
		c.events.Emit(ChatEvent{Type: "done"})
	} else {
		c.state.UpdateLastMessage(data, false)
		c.events.Emit(ChatEvent{Type: "token"})
	}
}

func (c *chatApp) openSettings() {
	c.showSettings.Set(true)
}

func (c *chatApp) closeSettings() {
	c.showSettings.Set(false)
}

func (c *chatApp) KeyMap() tui.KeyMap {
	km := tui.KeyMap{
		tui.OnKey(tui.KeyCtrlC, func(ke tui.KeyEvent) {
			if c.state.IsStreaming.Get() {
				c.events.Emit(ChatEvent{Type: "cancel"})
			} else {
				tui.Stop()
			}
		}),
		tui.OnKey(tui.KeyCtrlL, func(ke tui.KeyEvent) {
			c.state.ClearMessages()
		}),
		tui.OnKey(tui.KeyCtrlS, func(ke tui.KeyEvent) {
			c.openSettings()
		}),
		tui.OnRune('?', func(ke tui.KeyEvent) {
			c.showHelp.Set(!c.showHelp.Get())
		}),
	}

	// Close help on any key when shown
	if c.showHelp.Get() {
		km = append(km, tui.OnRunesStop(func(ke tui.KeyEvent) {
			c.showHelp.Set(false)
		}))
		km = append(km, tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			c.showHelp.Set(false)
		}))
	}

	return km
}

func SettingsScreen(c *chatApp) *settings.SettingsApp {
	return settings.NewSettingsApp(
		c.state.Provider,
		c.state.Model,
		c.state.Temperature,
		c.state.SystemPrompt,
		c.state.AvailableProviders,
		c.state.ProviderModels,
		c.closeSettings,
	)
}

func (c *chatApp) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
	)
	if c.showSettings.Get() {
		__tui_1 := tui.Mount(c, 0, func() tui.Component {
			return SettingsScreen(c)
		})
		__tui_0.AddChild(__tui_1)
	} else {
		__tui_2 := tui.Mount(c, 1, func() tui.Component {
			return Header(c.state)
		})
		__tui_0.AddChild(__tui_2)
		if c.showHelp.Get() {
			__tui_3 := tui.Mount(c, 2, func() tui.Component {
				return HelpOverlay()
			})
			__tui_0.AddChild(__tui_3)
		} else {
			__tui_4 := tui.Mount(c, 3, func() tui.Component {
				return MessageList(c.state, c.events)
			})
			__tui_0.AddChild(__tui_4)
		}
		if c.state.Error.Get() != "" {
			__tui_5 := tui.New(
				tui.WithBorder(tui.BorderRounded),
				tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Red)),
				tui.WithPadding(1),
				tui.WithMargin(1),
			)
			__tui_6 := tui.New(
				tui.WithText(" Error: "+c.state.Error.Get()),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_5.AddChild(__tui_6)
			__tui_0.AddChild(__tui_5)
		}
		__tui_7 := tui.Mount(c, 4, func() tui.Component {
			return InputBar(c.state, c.events)
		})
		__tui_0.AddChild(__tui_7)
	}

	return __tui_0
}
