// Code generated by tui generate. DO NOT EDIT.
// Source: chat.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/grindlemire/go-tui/examples/ai-chat/settings"
)

type chat struct {
	width        int
	textarea     *tui.TextArea
	showSettings *tui.State[bool]
	settingsView *settings.SettingsApp
}

func Chat(width int) *chat {
	c := &chat{
		width:        width,
		showSettings: tui.NewState(false),
	}

	c.textarea = tui.NewTextArea(
		tui.WithTextAreaWidth(width-2), // -2 for border
		tui.WithTextAreaBorder(tui.BorderRounded),
		tui.WithTextAreaPlaceholder("Type a message..."),
		tui.WithTextAreaOnSubmit(c.submit),
	)

	provider := tui.NewState("openai")
	model := tui.NewState("gpt-4.1-mini")
	temperature := tui.NewState(0.7)
	systemPrompt := tui.NewState("You are a helpful assistant.")
	availableProviders := []string{"openai", "anthropic", "ollama"}
	providerModels := map[string][]string{
		"openai":    {"gpt-4.1-mini", "gpt-4.1", "gpt-4o-mini"},
		"anthropic": {"claude-3-5-haiku-latest", "claude-3-7-sonnet-latest"},
		"ollama":    {"llama3.2", "mistral", "codellama"},
	}
	c.settingsView = settings.NewSettingsApp(
		provider,
		model,
		temperature,
		systemPrompt,
		availableProviders,
		providerModels,
		c.toggleSettings,
	)

	return c
}

func (c *chat) submit(text string) {
	if text == "" {
		return
	}
	c.textarea.Clear()
	c.updateHeight()
	tui.PrintAboveln("You: %s", text)
}

func (c *chat) toggleSettings() {
	if c.showSettings.Get() {
		_ = tui.ExitAlternateScreen()
		c.showSettings.Set(false)
		c.updateHeight()
		return
	}

	c.showSettings.Set(true)
	_ = tui.EnterAlternateScreen()
}

func (c *chat) KeyMap() tui.KeyMap {
	if c.showSettings.Get() {
		km := c.settingsView.KeyMap()
		km = append(km,
			tui.OnKey(tui.KeyCtrlC, func(ke tui.KeyEvent) { tui.Stop() }),
		)
		return km
	}

	km := c.textarea.KeyMap()
	km = append(km,
		tui.OnKeyStop(tui.KeyCtrlS, func(ke tui.KeyEvent) { c.toggleSettings() }),
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyCtrlC, func(ke tui.KeyEvent) { tui.Stop() }),
	)
	return km
}

func (c *chat) Watchers() []tui.Watcher {
	return c.textarea.Watchers()
}

func (c *chat) updateHeight() {
	h := c.textarea.Height()
	if h < 3 {
		h = 3
	}
	tui.SetInlineHeight(h)
}

func (c *chat) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if c.showSettings.Get() {
		__tui_1 := c.settingsView.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else {
		c.updateHeight()
		__tui_2 := c.textarea.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_2
		}
	}

	return __tui_0
}

func (c *chat) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*chat)
	if !ok {
		return
	}
	c.width = f.width
	c.textarea = f.textarea
	c.settingsView = f.settingsView
}

var _ tui.PropsUpdater = (*chat)(nil)

func (c *chat) BindApp(app *tui.App) {
	if c.showSettings != nil {
		c.showSettings.BindApp(app)
	}
}

var _ tui.AppBinder = (*chat)(nil)
