// Code generated by tui generate. DO NOT EDIT.
// Source: styling.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type stylingApp struct {
	scrollY *tui.State[int]
}

func Styling() *stylingApp {
	return &stylingApp{
		scrollY: tui.NewState(0),
	}
}

func (s *stylingApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { s.scrollY.Set(s.scrollY.Get() + 1) }),
		tui.OnRune('k', func(ke tui.KeyEvent) { s.scrollY.Set(s.scrollY.Get() - 1) }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { s.scrollY.Set(s.scrollY.Get() + 1) }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { s.scrollY.Set(s.scrollY.Get() - 1) }),
	}
}

func (s *stylingApp) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		s.scrollY.Set(s.scrollY.Get() - 1)
		return true
	case tui.MouseWheelDown:
		s.scrollY.Set(s.scrollY.Get() + 1)
		return true
	}
	return false
}

func (s *stylingApp) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithBorder(tui.BorderRounded),
		tui.WithHeightPercent(100.00),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, s.scrollY.Get()),
	)
	__tui_1 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_2 := tui.New(
		tui.WithText("Text Styles"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_4 := tui.New(
		tui.WithText("Bold text"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("Dim text"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_3.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText("Italic text"),
		tui.WithTextStyle(tui.NewStyle().Italic()),
	)
	__tui_3.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("Underlined text"),
		tui.WithTextStyle(tui.NewStyle().Underline()),
	)
	__tui_3.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("Strikethrough text"),
		tui.WithTextStyle(tui.NewStyle().Strikethrough()),
	)
	__tui_3.AddChild(__tui_8)
	__tui_9 := tui.New(
		tui.WithText("Reverse text"),
		tui.WithTextStyle(tui.NewStyle().Reverse()),
	)
	__tui_3.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText("Bold+Italic+Underline"),
		tui.WithTextStyle(tui.NewStyle().Bold().Italic().Underline()),
	)
	__tui_3.AddChild(__tui_10)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_11 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_13 := tui.New(
		tui.WithText("Text Colors"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_12.AddChild(__tui_13)
	__tui_14 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_15 := tui.New(
		tui.WithText("Red"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
	)
	__tui_14.AddChild(__tui_15)
	__tui_16 := tui.New(
		tui.WithText("Green"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_14.AddChild(__tui_16)
	__tui_17 := tui.New(
		tui.WithText("Blue"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue)),
	)
	__tui_14.AddChild(__tui_17)
	__tui_18 := tui.New(
		tui.WithText("Cyan"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_14.AddChild(__tui_18)
	__tui_19 := tui.New(
		tui.WithText("Magenta"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_14.AddChild(__tui_19)
	__tui_20 := tui.New(
		tui.WithText("Yellow"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
	)
	__tui_14.AddChild(__tui_20)
	__tui_21 := tui.New(
		tui.WithText("White"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_14.AddChild(__tui_21)
	__tui_12.AddChild(__tui_14)
	__tui_0.AddChild(__tui_12)
	__tui_22 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_22)
	__tui_23 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_24 := tui.New(
		tui.WithText("Bright Text Colors"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_23.AddChild(__tui_24)
	__tui_25 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_26 := tui.New(
		tui.WithText("Red"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightRed)),
	)
	__tui_25.AddChild(__tui_26)
	__tui_27 := tui.New(
		tui.WithText("Green"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightGreen)),
	)
	__tui_25.AddChild(__tui_27)
	__tui_28 := tui.New(
		tui.WithText("Blue"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightBlue)),
	)
	__tui_25.AddChild(__tui_28)
	__tui_29 := tui.New(
		tui.WithText("Cyan"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightCyan)),
	)
	__tui_25.AddChild(__tui_29)
	__tui_30 := tui.New(
		tui.WithText("Magenta"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightMagenta)),
	)
	__tui_25.AddChild(__tui_30)
	__tui_31 := tui.New(
		tui.WithText("Yellow"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightYellow)),
	)
	__tui_25.AddChild(__tui_31)
	__tui_32 := tui.New(
		tui.WithText("White"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightWhite)),
	)
	__tui_25.AddChild(__tui_32)
	__tui_23.AddChild(__tui_25)
	__tui_0.AddChild(__tui_23)
	__tui_33 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_33)
	__tui_34 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_35 := tui.New(
		tui.WithText("Background Colors"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_34.AddChild(__tui_35)
	__tui_36 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_37 := tui.New(
		tui.WithText("Red"),
		tui.WithBackground(tui.NewStyle().Background(tui.Red)),
	)
	__tui_36.AddChild(__tui_37)
	__tui_38 := tui.New(
		tui.WithText("Green"),
		tui.WithBackground(tui.NewStyle().Background(tui.Green)),
	)
	__tui_36.AddChild(__tui_38)
	__tui_39 := tui.New(
		tui.WithText("Blue"),
		tui.WithBackground(tui.NewStyle().Background(tui.Blue)),
	)
	__tui_36.AddChild(__tui_39)
	__tui_40 := tui.New(
		tui.WithText("Cyan"),
		tui.WithBackground(tui.NewStyle().Background(tui.Cyan)),
	)
	__tui_36.AddChild(__tui_40)
	__tui_41 := tui.New(
		tui.WithText("Magenta"),
		tui.WithBackground(tui.NewStyle().Background(tui.Magenta)),
	)
	__tui_36.AddChild(__tui_41)
	__tui_42 := tui.New(
		tui.WithText("Yellow"),
		tui.WithBackground(tui.NewStyle().Background(tui.Yellow)),
	)
	__tui_36.AddChild(__tui_42)
	__tui_43 := tui.New(
		tui.WithText("White"),
		tui.WithBackground(tui.NewStyle().Background(tui.White)),
	)
	__tui_36.AddChild(__tui_43)
	__tui_34.AddChild(__tui_36)
	__tui_0.AddChild(__tui_34)
	__tui_44 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_44)
	__tui_45 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_46 := tui.New(
		tui.WithText("Bright Background Colors"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_45.AddChild(__tui_46)
	__tui_47 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_48 := tui.New(
		tui.WithText("Red"),
		tui.WithBackground(tui.NewStyle().Background(tui.BrightRed)),
	)
	__tui_47.AddChild(__tui_48)
	__tui_49 := tui.New(
		tui.WithText("Green"),
		tui.WithBackground(tui.NewStyle().Background(tui.BrightGreen)),
	)
	__tui_47.AddChild(__tui_49)
	__tui_50 := tui.New(
		tui.WithText("Blue"),
		tui.WithBackground(tui.NewStyle().Background(tui.BrightBlue)),
	)
	__tui_47.AddChild(__tui_50)
	__tui_51 := tui.New(
		tui.WithText("Cyan"),
		tui.WithBackground(tui.NewStyle().Background(tui.BrightCyan)),
	)
	__tui_47.AddChild(__tui_51)
	__tui_52 := tui.New(
		tui.WithText("Magenta"),
		tui.WithBackground(tui.NewStyle().Background(tui.BrightMagenta)),
	)
	__tui_47.AddChild(__tui_52)
	__tui_53 := tui.New(
		tui.WithText("Yellow"),
		tui.WithBackground(tui.NewStyle().Background(tui.BrightYellow)),
	)
	__tui_47.AddChild(__tui_53)
	__tui_54 := tui.New(
		tui.WithText("White"),
		tui.WithBackground(tui.NewStyle().Background(tui.BrightWhite)),
	)
	__tui_47.AddChild(__tui_54)
	__tui_45.AddChild(__tui_47)
	__tui_0.AddChild(__tui_45)
	__tui_55 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_55)
	__tui_56 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_57 := tui.New(
		tui.WithText("Combined Foreground+Background"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_56.AddChild(__tui_57)
	__tui_58 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_59 := tui.New(
		tui.WithText("Error"),
		tui.WithBackground(tui.NewStyle().Background(tui.Red)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_58.AddChild(__tui_59)
	__tui_60 := tui.New(
		tui.WithText("Warning"),
		tui.WithBackground(tui.NewStyle().Background(tui.Yellow)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Black)),
	)
	__tui_58.AddChild(__tui_60)
	__tui_61 := tui.New(
		tui.WithText("Success"),
		tui.WithBackground(tui.NewStyle().Background(tui.Green)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_58.AddChild(__tui_61)
	__tui_62 := tui.New(
		tui.WithText("Info"),
		tui.WithBackground(tui.NewStyle().Background(tui.Blue)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_58.AddChild(__tui_62)
	__tui_63 := tui.New(
		tui.WithText("Highlight"),
		tui.WithBackground(tui.NewStyle().Background(tui.Cyan)),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Black)),
	)
	__tui_58.AddChild(__tui_63)
	__tui_56.AddChild(__tui_58)
	__tui_0.AddChild(__tui_56)
	__tui_64 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_64)
	__tui_65 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_66 := tui.New(
		tui.WithText("Border Styles"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_65.AddChild(__tui_66)
	__tui_67 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_68 := tui.New(
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_69 := tui.New(
		tui.WithText("Single"),
	)
	__tui_68.AddChild(__tui_69)
	__tui_67.AddChild(__tui_68)
	__tui_70 := tui.New(
		tui.WithBorder(tui.BorderDouble),
	)
	__tui_71 := tui.New(
		tui.WithText("Double"),
	)
	__tui_70.AddChild(__tui_71)
	__tui_67.AddChild(__tui_70)
	__tui_72 := tui.New(
		tui.WithBorder(tui.BorderRounded),
	)
	__tui_73 := tui.New(
		tui.WithText("Rounded"),
	)
	__tui_72.AddChild(__tui_73)
	__tui_67.AddChild(__tui_72)
	__tui_74 := tui.New(
		tui.WithBorder(tui.BorderThick),
	)
	__tui_75 := tui.New(
		tui.WithText("Thick"),
	)
	__tui_74.AddChild(__tui_75)
	__tui_67.AddChild(__tui_74)
	__tui_65.AddChild(__tui_67)
	__tui_0.AddChild(__tui_65)
	__tui_76 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_76)
	__tui_77 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_78 := tui.New(
		tui.WithText("Colored Borders"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_77.AddChild(__tui_78)
	__tui_79 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_80 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Red)),
	)
	__tui_81 := tui.New(
		tui.WithText("Red"),
	)
	__tui_80.AddChild(__tui_81)
	__tui_79.AddChild(__tui_80)
	__tui_82 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_83 := tui.New(
		tui.WithText("Green"),
	)
	__tui_82.AddChild(__tui_83)
	__tui_79.AddChild(__tui_82)
	__tui_84 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
	)
	__tui_85 := tui.New(
		tui.WithText("Blue"),
	)
	__tui_84.AddChild(__tui_85)
	__tui_79.AddChild(__tui_84)
	__tui_86 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_87 := tui.New(
		tui.WithText("Cyan"),
	)
	__tui_86.AddChild(__tui_87)
	__tui_79.AddChild(__tui_86)
	__tui_88 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_89 := tui.New(
		tui.WithText("Magenta"),
	)
	__tui_88.AddChild(__tui_89)
	__tui_79.AddChild(__tui_88)
	__tui_90 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Yellow)),
	)
	__tui_91 := tui.New(
		tui.WithText("Yellow"),
	)
	__tui_90.AddChild(__tui_91)
	__tui_79.AddChild(__tui_90)
	__tui_92 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_93 := tui.New(
		tui.WithText("White"),
	)
	__tui_92.AddChild(__tui_93)
	__tui_79.AddChild(__tui_92)
	__tui_94 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Black)),
	)
	__tui_95 := tui.New(
		tui.WithText("Black"),
	)
	__tui_94.AddChild(__tui_95)
	__tui_79.AddChild(__tui_94)
	__tui_77.AddChild(__tui_79)
	__tui_0.AddChild(__tui_77)
	__tui_96 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_96)
	__tui_97 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_98 := tui.New(
		tui.WithText("Text Gradients"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_97.AddChild(__tui_98)
	__tui_99 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_100 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_101 := tui.New(
		tui.WithText("Red to Blue"),
		tui.WithTextGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
	)
	__tui_100.AddChild(__tui_101)
	__tui_102 := tui.New(
		tui.WithText("Cyan to Magenta"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
	)
	__tui_100.AddChild(__tui_102)
	__tui_103 := tui.New(
		tui.WithText("Yellow to Red"),
		tui.WithTextGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientHorizontal)),
	)
	__tui_100.AddChild(__tui_103)
	__tui_104 := tui.New(
		tui.WithText("Green to Blue"),
		tui.WithTextGradient(tui.NewGradient(tui.Green, tui.Blue).WithDirection(tui.GradientHorizontal)),
	)
	__tui_100.AddChild(__tui_104)
	__tui_99.AddChild(__tui_100)
	__tui_105 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_106 := tui.New(
		tui.WithText("Vertical"),
		tui.WithTextGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientVertical)),
	)
	__tui_105.AddChild(__tui_106)
	__tui_107 := tui.New(
		tui.WithText("Diagonal Down"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientDiagonalDown)),
	)
	__tui_105.AddChild(__tui_107)
	__tui_108 := tui.New(
		tui.WithText("Diagonal Up"),
		tui.WithTextGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientDiagonalUp)),
	)
	__tui_105.AddChild(__tui_108)
	__tui_99.AddChild(__tui_105)
	__tui_109 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_110 := tui.New(
		tui.WithText("Bright Red to Blue"),
		tui.WithTextGradient(tui.NewGradient(tui.BrightRed, tui.BrightBlue).WithDirection(tui.GradientHorizontal)),
	)
	__tui_109.AddChild(__tui_110)
	__tui_111 := tui.New(
		tui.WithText("Bright Cyan to Magenta"),
		tui.WithTextGradient(tui.NewGradient(tui.BrightCyan, tui.BrightMagenta).WithDirection(tui.GradientHorizontal)),
	)
	__tui_109.AddChild(__tui_111)
	__tui_99.AddChild(__tui_109)
	__tui_97.AddChild(__tui_99)
	__tui_0.AddChild(__tui_97)
	__tui_112 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_112)
	__tui_113 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_114 := tui.New(
		tui.WithText("Background Gradients"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_113.AddChild(__tui_114)
	__tui_115 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_116 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_117 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_118 := tui.New(
		tui.WithText("Horizontal"),
	)
	__tui_117.AddChild(__tui_118)
	__tui_116.AddChild(__tui_117)
	__tui_119 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientVertical)),
		tui.WithPadding(1),
	)
	__tui_120 := tui.New(
		tui.WithText("Vertical"),
	)
	__tui_119.AddChild(__tui_120)
	__tui_116.AddChild(__tui_119)
	__tui_121 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientDiagonalDown)),
		tui.WithPadding(1),
	)
	__tui_122 := tui.New(
		tui.WithText("Diagonal Down"),
	)
	__tui_121.AddChild(__tui_122)
	__tui_116.AddChild(__tui_121)
	__tui_123 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Green, tui.Blue).WithDirection(tui.GradientDiagonalUp)),
		tui.WithPadding(1),
	)
	__tui_124 := tui.New(
		tui.WithText("Diagonal Up"),
	)
	__tui_123.AddChild(__tui_124)
	__tui_116.AddChild(__tui_123)
	__tui_115.AddChild(__tui_116)
	__tui_125 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_126 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.BrightRed, tui.BrightBlue).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_127 := tui.New(
		tui.WithText("Bright Colors"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_126.AddChild(__tui_127)
	__tui_125.AddChild(__tui_126)
	__tui_128 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.White, tui.Black).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_129 := tui.New(
		tui.WithText("White to Black"),
	)
	__tui_128.AddChild(__tui_129)
	__tui_125.AddChild(__tui_128)
	__tui_130 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Black, tui.White).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_131 := tui.New(
		tui.WithText("Black to White"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_130.AddChild(__tui_131)
	__tui_125.AddChild(__tui_130)
	__tui_115.AddChild(__tui_125)
	__tui_113.AddChild(__tui_115)
	__tui_0.AddChild(__tui_113)
	__tui_132 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_132)
	__tui_133 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_134 := tui.New(
		tui.WithText("Border Gradients"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_133.AddChild(__tui_134)
	__tui_135 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_136 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_137 := tui.New(
		tui.WithText("Red to Blue"),
	)
	__tui_136.AddChild(__tui_137)
	__tui_135.AddChild(__tui_136)
	__tui_138 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithBorderGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_139 := tui.New(
		tui.WithText("Cyan to Magenta"),
	)
	__tui_138.AddChild(__tui_139)
	__tui_135.AddChild(__tui_138)
	__tui_140 := tui.New(
		tui.WithBorder(tui.BorderDouble),
		tui.WithBorderGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_141 := tui.New(
		tui.WithText("Yellow to Red"),
	)
	__tui_140.AddChild(__tui_141)
	__tui_135.AddChild(__tui_140)
	__tui_142 := tui.New(
		tui.WithBorder(tui.BorderThick),
		tui.WithBorderGradient(tui.NewGradient(tui.Green, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_143 := tui.New(
		tui.WithText("Green to Blue"),
	)
	__tui_142.AddChild(__tui_143)
	__tui_135.AddChild(__tui_142)
	__tui_133.AddChild(__tui_135)
	__tui_0.AddChild(__tui_133)
	__tui_144 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_144)
	__tui_145 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.White)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(0),
	)
	__tui_146 := tui.New(
		tui.WithText("Combined Gradients"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_145.AddChild(__tui_146)
	__tui_147 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_148 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithBorderGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientHorizontal)),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_149 := tui.New(
		tui.WithText("Text+Bg+Border"),
		tui.WithTextGradient(tui.NewGradient(tui.White, tui.Black).WithDirection(tui.GradientHorizontal)),
	)
	__tui_148.AddChild(__tui_149)
	__tui_147.AddChild(__tui_148)
	__tui_150 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientVertical)),
		tui.WithBorderGradient(tui.NewGradient(tui.Green, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_151 := tui.New(
		tui.WithText("All Gradients"),
		tui.WithTextGradient(tui.NewGradient(tui.BrightRed, tui.BrightBlue).WithDirection(tui.GradientHorizontal)),
	)
	__tui_150.AddChild(__tui_151)
	__tui_147.AddChild(__tui_150)
	__tui_145.AddChild(__tui_147)
	__tui_0.AddChild(__tui_145)
	__tui_152 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_152)
	__tui_153 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_153)

	return __tui_0
}
