// Code generated by tui generate. DO NOT EDIT.
// Source: events.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type explorer struct {
	lastKey  *tui.State[string]
	keyCount *tui.State[int]
}

func Explorer() *explorer {
	return &explorer{
		lastKey:  tui.NewState("(none)"),
		keyCount: tui.NewState(0),
	}
}

func (e *explorer) record(name string) {
	e.keyCount.Set(e.keyCount.Get() + 1)
	e.lastKey.Set(name)
}

func (e *explorer) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRuneStop('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRunes(func(ke tui.KeyEvent) {
			e.record(fmt.Sprintf("'%c' (rune)", ke.Rune))
		}),
		// With Kitty keyboard protocol, Ctrl+H/I/M arrive as KeyRune
		// events with ModCtrl and are matched by OnRuneMod.
		// Without Kitty, they are indistinguishable from Backspace/Tab/Enter
		// and match the OnKey handlers below instead.
		tui.OnRuneMod('h', tui.ModCtrl, func(ke tui.KeyEvent) { e.record("Ctrl+'h' (rune)") }),
		tui.OnRuneMod('i', tui.ModCtrl, func(ke tui.KeyEvent) { e.record("Ctrl+'i' (rune)") }),
		tui.OnRuneMod('m', tui.ModCtrl, func(ke tui.KeyEvent) { e.record("Ctrl+'m' (rune)") }),
		tui.OnKey(tui.KeyEnter, func(ke tui.KeyEvent) { e.record("Enter") }),
		tui.OnKey(tui.KeyTab, func(ke tui.KeyEvent) { e.record("Tab") }),
		tui.OnKey(tui.KeyBackspace, func(ke tui.KeyEvent) { e.record("Backspace") }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { e.record("Up") }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { e.record("Down") }),
		tui.OnKey(tui.KeyLeft, func(ke tui.KeyEvent) { e.record("Left") }),
		tui.OnKey(tui.KeyRight, func(ke tui.KeyEvent) { e.record("Right") }),
		tui.OnRuneMod('a', tui.ModCtrl, func(ke tui.KeyEvent) { e.record("Ctrl+A") }),
		tui.OnRuneMod('s', tui.ModCtrl, func(ke tui.KeyEvent) { e.record("Ctrl+S") }),
	}
}

func (e *explorer) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithText("Keyboard Explorer"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_4 := tui.New(
		tui.WithText("Last Key:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(e.lastKey.Get()),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_3.AddChild(__tui_5)
	__tui_0.AddChild(__tui_3)
	__tui_6 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_7 := tui.New(
		tui.WithText("Key Count:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_6.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText(fmt.Sprintf("%d", e.keyCount.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_6.AddChild(__tui_8)
	__tui_0.AddChild(__tui_6)
	__tui_9 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText("Press any key to see it displayed above"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithText("Press q or Esc to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_11)

	return __tui_0
}

func (e *explorer) BindApp(app *tui.App) {
	if e.lastKey != nil {
		e.lastKey.BindApp(app)
	}
	if e.keyCount != nil {
		e.keyCount.BindApp(app)
	}
}

var _ tui.AppBinder = (*explorer)(nil)
