// Code generated by tui generate. DO NOT EDIT.
// Source: streaming.gsx

package main

import (
	"fmt"
	"time"

	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func tick(elapsed *tui.State[int]) func() {
	return func() {
		elapsed.Set(elapsed.Get() + 1)
	}
}

func addLine(lineCount *tui.State[int], content *element.Element) func(string) {
	return func(line string) {
		lineCount.Set(lineCount.Get() + 1)

		stayAtBottom := content.IsAtBottom()

		lineElem := element.New(
			element.WithText(line),
			element.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		content.AddChild(lineElem)

		if stayAtBottom {
			content.ScrollToBottom()
		}
	}
}

func handleScrollKeys(content *element.Element) func(tui.KeyEvent) {
	return func(e tui.KeyEvent) {
		switch e.Rune {
		case 'j':
			content.ScrollBy(0, 1)
		case 'k':
			content.ScrollBy(0, -1)
		}
	}
}

type StreamingView struct {
	Root     *element.Element
	watchers []tui.Watcher
	Content  *element.Element
}

func (v StreamingView) GetRoot() tui.Renderable { return v.Root }

func (v StreamingView) GetWatchers() []tui.Watcher { return v.watchers }

func Streaming(dataCh <-chan string) StreamingView {
	var view StreamingView
	var watchers []tui.Watcher

	var Content *element.Element

	lineCount := tui.NewState(0)
	elapsed := tui.NewState(0)
	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(1),
	)
	__tui_1 := element.New(
		element.WithText("Streaming with Channels and Timers"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := element.New(
		element.WithHR(),
		element.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	Content = element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithDirection(layout.Column),
		element.WithFlexGrow(1),
		element.WithScrollable(element.ScrollVertical),
		element.WithFocusable(true),
	)
	__tui_0.AddChild(Content)
	__tui_3 := element.New(
		element.WithDirection(layout.Row),
		element.WithGap(2),
	)
	__tui_4 := element.New()
	__tui_5 := element.New(element.WithText("Lines:"))
	__tui_4.AddChild(__tui_5)
	__tui_6 := element.New(element.WithText(fmt.Sprintf("%d", lineCount.Get())))
	__tui_4.AddChild(__tui_6)
	__tui_3.AddChild(__tui_4)
	__tui_7 := element.New()
	__tui_8 := element.New(element.WithText("Elapsed:"))
	__tui_7.AddChild(__tui_8)
	__tui_9 := element.New(element.WithText(fmt.Sprintf("%ds", elapsed.Get())))
	__tui_7.AddChild(__tui_9)
	__tui_3.AddChild(__tui_7)
	__tui_0.AddChild(__tui_3)
	__tui_10 := element.New(
		element.WithText("Press q to quit"),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)

	// Attach handlers (deferred until refs are assigned)
	Content.SetOnKeyPress(handleScrollKeys(Content))

	// Attach watchers (deferred until refs are assigned)
	__tui_0.AddWatcher(tui.OnTimer(time.Second, tick(elapsed)))
	__tui_0.AddWatcher(tui.Watch(dataCh, addLine(lineCount, Content)))

	// State bindings
	lineCount.Bind(func(_ int) {
		__tui_6.SetText(fmt.Sprintf("%d", lineCount.Get()))
	})
	elapsed.Bind(func(_ int) {
		__tui_9.SetText(fmt.Sprintf("%ds", elapsed.Get()))
	})

	view = StreamingView{
		Root:     __tui_0,
		watchers: watchers,
		Content:  Content,
	}
	return view
}
