// Code generated by tui generate. DO NOT EDIT.
// Source: streaming.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

type streamingApp struct {
	dataCh    <-chan string
	lineCount *tui.State[int]
	elapsed   *tui.State[int]
	content   *tui.Ref
}

func Streaming(dataCh <-chan string) *streamingApp {
	return &streamingApp{
		dataCh:    dataCh,
		lineCount: tui.NewState(0),
		elapsed:   tui.NewState(0),
		content:   tui.NewRef(),
	}
}

func (s *streamingApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
		// Custom j/k scrolling
		tui.OnRune('j', func(ke tui.KeyEvent) {
			if s.content.El() != nil {
				s.content.El().ScrollBy(0, 1)
			}
		}),
		tui.OnRune('k', func(ke tui.KeyEvent) {
			if s.content.El() != nil {
				s.content.El().ScrollBy(0, -1)
			}
		}),
	}
}

func (s *streamingApp) tick() {
	s.elapsed.Set(s.elapsed.Get() + 1)
}

func (s *streamingApp) addLine(line string) {
	s.lineCount.Set(s.lineCount.Get() + 1)

	el := s.content.El()
	stayAtBottom := el.IsAtBottom()

	lineElem := tui.New(
		tui.WithText(line),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	el.AddChild(lineElem)

	if stayAtBottom {
		el.ScrollToBottom()
	}
}

func (s *streamingApp) Render() *tui.Element {
	content := s.content
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Streaming with Channels and Timers"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithFocusable(true),
	)
	content.Set(__tui_3)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_5 := tui.New()
	__tui_6 := tui.New(tui.WithText("Lines:"))
	__tui_5.AddChild(__tui_6)
	__tui_7 := tui.New(tui.WithText(fmt.Sprintf("%d", s.lineCount.Get())))
	__tui_5.AddChild(__tui_7)
	__tui_4.AddChild(__tui_5)
	__tui_8 := tui.New()
	__tui_9 := tui.New(tui.WithText("Elapsed:"))
	__tui_8.AddChild(__tui_9)
	__tui_10 := tui.New(tui.WithText(fmt.Sprintf("%ds", s.elapsed.Get())))
	__tui_8.AddChild(__tui_10)
	__tui_4.AddChild(__tui_8)
	__tui_0.AddChild(__tui_4)
	__tui_11 := tui.New(
		tui.WithText("Press q to quit, j/k to scroll"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_11)

	// Attach watchers (deferred until refs are assigned)
	__tui_0.AddWatcher(tui.OnTimer(time.Second, s.tick))
	__tui_0.AddWatcher(tui.Watch(s.dataCh, s.addLine))

	return __tui_0
}
