// Code generated by tui generate. DO NOT EDIT.
// Source: styling.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type stylingApp struct {
	scrollY *tui.State[int]
	content *tui.Ref
}

func Styling() *stylingApp {
	return &stylingApp{
		scrollY: tui.NewState(0),
		content: tui.NewRef(),
	}
}

func (s *stylingApp) scrollBy(delta int) {
	el := s.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := s.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	s.scrollY.Set(newY)
}

func (s *stylingApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { s.scrollBy(1) }),
		tui.OnRune('k', func(ke tui.KeyEvent) { s.scrollBy(-1) }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { s.scrollBy(1) }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { s.scrollBy(-1) }),
	}
}

func (s *stylingApp) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		s.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		s.scrollBy(1)
		return true
	}
	return false
}

func (s *stylingApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithHeightPercent(100.00),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, s.scrollY.Get()),
	)
	s.content.Set(__tui_0)
	__tui_1 := tui.New(
		tui.WithText("Style Guide"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_4 := tui.New(
		tui.WithText("Text Colors"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_6 := tui.New(
		tui.WithText("red"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
	)
	__tui_5.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("green"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_5.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("blue"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue)),
	)
	__tui_5.AddChild(__tui_8)
	__tui_9 := tui.New(
		tui.WithText("cyan"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_5.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText("magenta"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_5.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithText("yellow"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
	)
	__tui_5.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText("white"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_5.AddChild(__tui_12)
	__tui_3.AddChild(__tui_5)
	__tui_13 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_14 := tui.New(
		tui.WithText("bright-red"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightRed)),
	)
	__tui_13.AddChild(__tui_14)
	__tui_15 := tui.New(
		tui.WithText("bright-green"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightGreen)),
	)
	__tui_13.AddChild(__tui_15)
	__tui_16 := tui.New(
		tui.WithText("bright-blue"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightBlue)),
	)
	__tui_13.AddChild(__tui_16)
	__tui_17 := tui.New(
		tui.WithText("bright-cyan"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightCyan)),
	)
	__tui_13.AddChild(__tui_17)
	__tui_18 := tui.New(
		tui.WithText("bright-magenta"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.BrightMagenta)),
	)
	__tui_13.AddChild(__tui_18)
	__tui_3.AddChild(__tui_13)
	__tui_2.AddChild(__tui_3)
	__tui_19 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_20 := tui.New(
		tui.WithText("Text Styles"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_19.AddChild(__tui_20)
	__tui_21 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_22 := tui.New(
		tui.WithText("Bold"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_21.AddChild(__tui_22)
	__tui_23 := tui.New(
		tui.WithText("Dim"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_21.AddChild(__tui_23)
	__tui_24 := tui.New(
		tui.WithText("Italic"),
		tui.WithTextStyle(tui.NewStyle().Italic()),
	)
	__tui_21.AddChild(__tui_24)
	__tui_19.AddChild(__tui_21)
	__tui_25 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_26 := tui.New(
		tui.WithText("Underline"),
		tui.WithTextStyle(tui.NewStyle().Underline()),
	)
	__tui_25.AddChild(__tui_26)
	__tui_27 := tui.New(
		tui.WithText("Strikethrough"),
		tui.WithTextStyle(tui.NewStyle().Strikethrough()),
	)
	__tui_25.AddChild(__tui_27)
	__tui_28 := tui.New(
		tui.WithText("Reverse"),
		tui.WithTextStyle(tui.NewStyle().Reverse()),
	)
	__tui_25.AddChild(__tui_28)
	__tui_19.AddChild(__tui_25)
	__tui_29 := tui.New(
		tui.WithText("Combined styles"),
		tui.WithTextStyle(tui.NewStyle().Bold().Italic().Underline()),
	)
	__tui_19.AddChild(__tui_29)
	__tui_2.AddChild(__tui_19)
	__tui_0.AddChild(__tui_2)
	__tui_30 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_31 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_32 := tui.New(
		tui.WithText("Borders"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_31.AddChild(__tui_32)
	__tui_33 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_34 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_35 := tui.New(
		tui.WithText("Single"),
	)
	__tui_34.AddChild(__tui_35)
	__tui_33.AddChild(__tui_34)
	__tui_36 := tui.New(
		tui.WithBorder(tui.BorderDouble),
		tui.WithPadding(1),
	)
	__tui_37 := tui.New(
		tui.WithText("Double"),
	)
	__tui_36.AddChild(__tui_37)
	__tui_33.AddChild(__tui_36)
	__tui_38 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_39 := tui.New(
		tui.WithText("Rounded"),
	)
	__tui_38.AddChild(__tui_39)
	__tui_33.AddChild(__tui_38)
	__tui_40 := tui.New(
		tui.WithBorder(tui.BorderThick),
		tui.WithPadding(1),
	)
	__tui_41 := tui.New(
		tui.WithText("Thick"),
	)
	__tui_40.AddChild(__tui_41)
	__tui_33.AddChild(__tui_40)
	__tui_31.AddChild(__tui_33)
	__tui_42 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_43 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Red)),
		tui.WithPadding(1),
	)
	__tui_44 := tui.New(
		tui.WithText("red"),
	)
	__tui_43.AddChild(__tui_44)
	__tui_42.AddChild(__tui_43)
	__tui_45 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Green)),
		tui.WithPadding(1),
	)
	__tui_46 := tui.New(
		tui.WithText("green"),
	)
	__tui_45.AddChild(__tui_46)
	__tui_42.AddChild(__tui_45)
	__tui_47 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
		tui.WithPadding(1),
	)
	__tui_48 := tui.New(
		tui.WithText("blue"),
	)
	__tui_47.AddChild(__tui_48)
	__tui_42.AddChild(__tui_47)
	__tui_49 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithPadding(1),
	)
	__tui_50 := tui.New(
		tui.WithText("cyan"),
	)
	__tui_49.AddChild(__tui_50)
	__tui_42.AddChild(__tui_49)
	__tui_51 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Magenta)),
		tui.WithPadding(1),
	)
	__tui_52 := tui.New(
		tui.WithText("magenta"),
	)
	__tui_51.AddChild(__tui_52)
	__tui_42.AddChild(__tui_51)
	__tui_53 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Yellow)),
		tui.WithPadding(1),
	)
	__tui_54 := tui.New(
		tui.WithText("yellow"),
	)
	__tui_53.AddChild(__tui_54)
	__tui_42.AddChild(__tui_53)
	__tui_31.AddChild(__tui_42)
	__tui_30.AddChild(__tui_31)
	__tui_55 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_56 := tui.New(
		tui.WithText("Gradients"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_55.AddChild(__tui_56)
	__tui_57 := tui.New(
		tui.WithText("Horizontal red to blue"),
		tui.WithTextGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
	)
	__tui_55.AddChild(__tui_57)
	__tui_58 := tui.New(
		tui.WithText("Horizontal cyan to magenta"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
	)
	__tui_55.AddChild(__tui_58)
	__tui_59 := tui.New(
		tui.WithText("Vertical yellow to red"),
		tui.WithTextGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientVertical)),
	)
	__tui_55.AddChild(__tui_59)
	__tui_60 := tui.New(
		tui.WithText("Diagonal green to blue"),
		tui.WithTextGradient(tui.NewGradient(tui.Green, tui.Blue).WithDirection(tui.GradientDiagonalDown)),
	)
	__tui_55.AddChild(__tui_60)
	__tui_30.AddChild(__tui_55)
	__tui_0.AddChild(__tui_30)
	__tui_61 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_62 := tui.New(
		tui.WithText("Backgrounds"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_61.AddChild(__tui_62)
	__tui_63 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_64 := tui.New(
		tui.WithText("red"),
		tui.WithBackground(tui.NewStyle().Background(tui.Red)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_63.AddChild(__tui_64)
	__tui_65 := tui.New(
		tui.WithText("green"),
		tui.WithBackground(tui.NewStyle().Background(tui.Green)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_63.AddChild(__tui_65)
	__tui_66 := tui.New(
		tui.WithText("blue"),
		tui.WithBackground(tui.NewStyle().Background(tui.Blue)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_63.AddChild(__tui_66)
	__tui_67 := tui.New(
		tui.WithText("cyan"),
		tui.WithBackground(tui.NewStyle().Background(tui.Cyan)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Black)),
	)
	__tui_63.AddChild(__tui_67)
	__tui_68 := tui.New(
		tui.WithText("magenta"),
		tui.WithBackground(tui.NewStyle().Background(tui.Magenta)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_63.AddChild(__tui_68)
	__tui_69 := tui.New(
		tui.WithText("yellow"),
		tui.WithBackground(tui.NewStyle().Background(tui.Yellow)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Black)),
	)
	__tui_63.AddChild(__tui_69)
	__tui_61.AddChild(__tui_63)
	__tui_70 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_71 := tui.New(
		tui.WithText("Error"),
		tui.WithBackground(tui.NewStyle().Background(tui.Red)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White).Bold()),
	)
	__tui_70.AddChild(__tui_71)
	__tui_72 := tui.New(
		tui.WithText("Warning"),
		tui.WithBackground(tui.NewStyle().Background(tui.Yellow)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Black).Bold()),
	)
	__tui_70.AddChild(__tui_72)
	__tui_73 := tui.New(
		tui.WithText("Success"),
		tui.WithBackground(tui.NewStyle().Background(tui.Green)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White).Bold()),
	)
	__tui_70.AddChild(__tui_73)
	__tui_74 := tui.New(
		tui.WithText("Info"),
		tui.WithBackground(tui.NewStyle().Background(tui.Blue)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White).Bold()),
	)
	__tui_70.AddChild(__tui_74)
	__tui_75 := tui.New(
		tui.WithText("Highlight"),
		tui.WithBackground(tui.NewStyle().Background(tui.Cyan)),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Black)),
	)
	__tui_70.AddChild(__tui_75)
	__tui_61.AddChild(__tui_70)
	__tui_0.AddChild(__tui_61)
	__tui_76 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_77 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_78 := tui.New(
		tui.WithText("Background Gradients"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_77.AddChild(__tui_78)
	__tui_79 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_80 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_81 := tui.New(
		tui.WithText("Horizontal"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_80.AddChild(__tui_81)
	__tui_79.AddChild(__tui_80)
	__tui_82 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientVertical)),
		tui.WithPadding(1),
	)
	__tui_83 := tui.New(
		tui.WithText("Vertical"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_82.AddChild(__tui_83)
	__tui_79.AddChild(__tui_82)
	__tui_84 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientDiagonalDown)),
		tui.WithPadding(1),
	)
	__tui_85 := tui.New(
		tui.WithText("Diagonal"),
	)
	__tui_84.AddChild(__tui_85)
	__tui_79.AddChild(__tui_84)
	__tui_77.AddChild(__tui_79)
	__tui_76.AddChild(__tui_77)
	__tui_86 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_87 := tui.New(
		tui.WithText("Border Gradients"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_86.AddChild(__tui_87)
	__tui_88 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_89 := tui.New(
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_90 := tui.New(
		tui.WithText("Red-Blue"),
	)
	__tui_89.AddChild(__tui_90)
	__tui_88.AddChild(__tui_89)
	__tui_91 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithBorderGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_92 := tui.New(
		tui.WithText("Cyan-Magenta"),
	)
	__tui_91.AddChild(__tui_92)
	__tui_88.AddChild(__tui_91)
	__tui_93 := tui.New(
		tui.WithBorder(tui.BorderDouble),
		tui.WithBorderGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientHorizontal)),
		tui.WithPadding(1),
	)
	__tui_94 := tui.New(
		tui.WithText("Yellow-Red"),
	)
	__tui_93.AddChild(__tui_94)
	__tui_88.AddChild(__tui_93)
	__tui_86.AddChild(__tui_88)
	__tui_76.AddChild(__tui_86)
	__tui_0.AddChild(__tui_76)
	__tui_95 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_96 := tui.New(
		tui.WithText("Combined Gradients"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_95.AddChild(__tui_96)
	__tui_97 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_98 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Red, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithBorderGradient(tui.NewGradient(tui.Yellow, tui.Red).WithDirection(tui.GradientHorizontal)),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_99 := tui.New(
		tui.WithText("Text+Bg+Border"),
		tui.WithTextGradient(tui.NewGradient(tui.White, tui.Black).WithDirection(tui.GradientHorizontal)),
	)
	__tui_98.AddChild(__tui_99)
	__tui_97.AddChild(__tui_98)
	__tui_100 := tui.New(
		tui.WithBackgroundGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientVertical)),
		tui.WithBorderGradient(tui.NewGradient(tui.Green, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
	)
	__tui_101 := tui.New(
		tui.WithText("All Gradients"),
		tui.WithTextGradient(tui.NewGradient(tui.BrightRed, tui.BrightBlue).WithDirection(tui.GradientHorizontal)),
	)
	__tui_100.AddChild(__tui_101)
	__tui_97.AddChild(__tui_100)
	__tui_95.AddChild(__tui_97)
	__tui_0.AddChild(__tui_95)
	__tui_102 := tui.New(
		tui.WithText("j/k to scroll|q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_102)

	return __tui_0
}

func (s *stylingApp) BindApp(app *tui.App) {
	if s.scrollY != nil {
		s.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*stylingApp)(nil)
