// Code generated by tui generate. DO NOT EDIT.
// Source: loops.gsx

package main

import (
	"fmt"

	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

type LoopsView struct {
	Root     *element.Element
	watchers []tui.Watcher
}

func (v LoopsView) GetRoot() tui.Renderable { return v.Root }

func (v LoopsView) GetWatchers() []tui.Watcher { return v.watchers }

func Loops(items []string, selected int) LoopsView {
	var view LoopsView
	var watchers []tui.Watcher

	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(2),
		element.WithBorder(tui.BorderRounded),
	)
	__tui_1 := element.New(
		element.WithText("Loop Rendering"),
		element.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := element.New(
		element.WithHR(),
		element.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := element.New(
		element.WithDirection(layout.Column),
	)
	for i, item := range items {
		_ = i
		if i == selected {
			__tui_4 := element.New(
				element.WithText(fmt.Sprintf("> %d. %s", i+1, item)),
				element.WithBackground(tui.NewStyle().Background(tui.Blue)),
				element.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
			)
			__tui_3.AddChild(__tui_4)
		} else {
			__tui_5 := element.New(
				element.WithText(fmt.Sprintf("  %d. %s", i+1, item)),
			)
			__tui_3.AddChild(__tui_5)
		}
	}
	__tui_0.AddChild(__tui_3)
	__tui_6 := element.New(
		element.WithWidth(0),
		element.WithHeight(1),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := element.New(
		element.WithText("Press j/k to move, q to quit"),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_7)

	view = LoopsView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
