// Code generated by tui generate. DO NOT EDIT.
// Source: keyboard.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type keyboardApp struct {
	lastKey      *tui.State[string]
	keyCount     *tui.State[int]
	pressedEnter *tui.State[bool]
	pressedTab   *tui.State[bool]
	pressedBksp  *tui.State[bool]
	pressedDel   *tui.State[bool]
	pressedUp    *tui.State[bool]
	pressedDown  *tui.State[bool]
	pressedLeft  *tui.State[bool]
	pressedRight *tui.State[bool]
	pressedHome  *tui.State[bool]
	pressedEnd   *tui.State[bool]
	pressedPgUp  *tui.State[bool]
	pressedPgDn  *tui.State[bool]
	pressedCtrlA *tui.State[bool]
	pressedCtrlD *tui.State[bool]
	pressedCtrlN *tui.State[bool]
	pressedCtrlR *tui.State[bool]
	pressedCtrlS *tui.State[bool]
	pressedCtrlW *tui.State[bool]
	pressedCtrlX *tui.State[bool]
	pressedCtrlZ *tui.State[bool]
}

func Keyboard() *keyboardApp {
	return &keyboardApp{
		lastKey:      tui.NewState("(none)"),
		keyCount:     tui.NewState(0),
		pressedEnter: tui.NewState(false),
		pressedTab:   tui.NewState(false),
		pressedBksp:  tui.NewState(false),
		pressedDel:   tui.NewState(false),
		pressedUp:    tui.NewState(false),
		pressedDown:  tui.NewState(false),
		pressedLeft:  tui.NewState(false),
		pressedRight: tui.NewState(false),
		pressedHome:  tui.NewState(false),
		pressedEnd:   tui.NewState(false),
		pressedPgUp:  tui.NewState(false),
		pressedPgDn:  tui.NewState(false),
		pressedCtrlA: tui.NewState(false),
		pressedCtrlD: tui.NewState(false),
		pressedCtrlN: tui.NewState(false),
		pressedCtrlR: tui.NewState(false),
		pressedCtrlS: tui.NewState(false),
		pressedCtrlW: tui.NewState(false),
		pressedCtrlX: tui.NewState(false),
		pressedCtrlZ: tui.NewState(false),
	}
}

func (k *keyboardApp) record(name string) {
	k.keyCount.Set(k.keyCount.Get() + 1)
	k.lastKey.Set(name)
}

func (k *keyboardApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRuneStop('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRunes(func(ke tui.KeyEvent) {
			k.record(fmt.Sprintf("'%c' (rune)", ke.Rune))
		}),
		tui.OnKey(tui.KeyEnter, func(ke tui.KeyEvent) { k.pressedEnter.Set(true); k.record("Enter") }),
		tui.OnKey(tui.KeyTab, func(ke tui.KeyEvent) { k.pressedTab.Set(true); k.record("Tab") }),
		tui.OnKey(tui.KeyBackspace, func(ke tui.KeyEvent) { k.pressedBksp.Set(true); k.record("Backspace") }),
		tui.OnKey(tui.KeyDelete, func(ke tui.KeyEvent) { k.pressedDel.Set(true); k.record("Delete") }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { k.pressedUp.Set(true); k.record("Up") }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { k.pressedDown.Set(true); k.record("Down") }),
		tui.OnKey(tui.KeyLeft, func(ke tui.KeyEvent) { k.pressedLeft.Set(true); k.record("Left") }),
		tui.OnKey(tui.KeyRight, func(ke tui.KeyEvent) { k.pressedRight.Set(true); k.record("Right") }),
		tui.OnKey(tui.KeyHome, func(ke tui.KeyEvent) { k.pressedHome.Set(true); k.record("Home") }),
		tui.OnKey(tui.KeyEnd, func(ke tui.KeyEvent) { k.pressedEnd.Set(true); k.record("End") }),
		tui.OnKey(tui.KeyPageUp, func(ke tui.KeyEvent) { k.pressedPgUp.Set(true); k.record("PgUp") }),
		tui.OnKey(tui.KeyPageDown, func(ke tui.KeyEvent) { k.pressedPgDn.Set(true); k.record("PgDn") }),
		tui.OnKey(tui.KeyCtrlA, func(ke tui.KeyEvent) { k.pressedCtrlA.Set(true); k.record("Ctrl+A") }),
		tui.OnKey(tui.KeyCtrlD, func(ke tui.KeyEvent) { k.pressedCtrlD.Set(true); k.record("Ctrl+D") }),
		tui.OnKey(tui.KeyCtrlN, func(ke tui.KeyEvent) { k.pressedCtrlN.Set(true); k.record("Ctrl+N") }),
		tui.OnKey(tui.KeyCtrlR, func(ke tui.KeyEvent) { k.pressedCtrlR.Set(true); k.record("Ctrl+R") }),
		tui.OnKey(tui.KeyCtrlS, func(ke tui.KeyEvent) { k.pressedCtrlS.Set(true); k.record("Ctrl+S") }),
		tui.OnKey(tui.KeyCtrlW, func(ke tui.KeyEvent) { k.pressedCtrlW.Set(true); k.record("Ctrl+W") }),
		tui.OnKey(tui.KeyCtrlX, func(ke tui.KeyEvent) { k.pressedCtrlX.Set(true); k.record("Ctrl+X") }),
		tui.OnKey(tui.KeyCtrlZ, func(ke tui.KeyEvent) { k.pressedCtrlZ.Set(true); k.record("Ctrl+Z") }),
	}
}

func keyLabel(label string, pressed bool) string {
	if pressed {
		return "✓ " + label
	}
	return "· " + label
}

func keyStyle(pressed bool) string {
	if pressed {
		return "text-green font-bold"
	}
	return "font-dim"
}

func (k *keyboardApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithText("Keyboard Explorer"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_4 := tui.New(
		tui.WithText("Last Key:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(k.lastKey.Get()),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_3.AddChild(__tui_5)
	__tui_0.AddChild(__tui_3)
	__tui_6 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_7 := tui.New(
		tui.WithText("Key Count:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_6.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText(fmt.Sprintf("%d", k.keyCount.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_6.AddChild(__tui_8)
	__tui_0.AddChild(__tui_6)
	__tui_9 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_11 := tui.New(
		tui.WithText("Special Keys"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_13 := tui.New(
		tui.WithText(keyLabel("Enter", k.pressedEnter.Get())),
	)
	__tui_12.AddChild(__tui_13)
	__tui_14 := tui.New(
		tui.WithText(keyLabel("Tab", k.pressedTab.Get())),
	)
	__tui_12.AddChild(__tui_14)
	__tui_15 := tui.New(
		tui.WithText(keyLabel("Bksp", k.pressedBksp.Get())),
	)
	__tui_12.AddChild(__tui_15)
	__tui_16 := tui.New(
		tui.WithText(keyLabel("Del", k.pressedDel.Get())),
	)
	__tui_12.AddChild(__tui_16)
	__tui_10.AddChild(__tui_12)
	__tui_17 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_18 := tui.New(
		tui.WithText(keyLabel("Up", k.pressedUp.Get())),
	)
	__tui_17.AddChild(__tui_18)
	__tui_19 := tui.New(
		tui.WithText(keyLabel("Down", k.pressedDown.Get())),
	)
	__tui_17.AddChild(__tui_19)
	__tui_20 := tui.New(
		tui.WithText(keyLabel("Left", k.pressedLeft.Get())),
	)
	__tui_17.AddChild(__tui_20)
	__tui_21 := tui.New(
		tui.WithText(keyLabel("Right", k.pressedRight.Get())),
	)
	__tui_17.AddChild(__tui_21)
	__tui_10.AddChild(__tui_17)
	__tui_22 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_23 := tui.New(
		tui.WithText(keyLabel("Home", k.pressedHome.Get())),
	)
	__tui_22.AddChild(__tui_23)
	__tui_24 := tui.New(
		tui.WithText(keyLabel("End", k.pressedEnd.Get())),
	)
	__tui_22.AddChild(__tui_24)
	__tui_25 := tui.New(
		tui.WithText(keyLabel("PgUp", k.pressedPgUp.Get())),
	)
	__tui_22.AddChild(__tui_25)
	__tui_26 := tui.New(
		tui.WithText(keyLabel("PgDn", k.pressedPgDn.Get())),
	)
	__tui_22.AddChild(__tui_26)
	__tui_10.AddChild(__tui_22)
	__tui_9.AddChild(__tui_10)
	__tui_27 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_28 := tui.New(
		tui.WithText("Ctrl Keys"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_27.AddChild(__tui_28)
	__tui_29 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_30 := tui.New(
		tui.WithText(keyLabel("Ctrl+A", k.pressedCtrlA.Get())),
	)
	__tui_29.AddChild(__tui_30)
	__tui_31 := tui.New(
		tui.WithText(keyLabel("Ctrl+D", k.pressedCtrlD.Get())),
	)
	__tui_29.AddChild(__tui_31)
	__tui_32 := tui.New(
		tui.WithText(keyLabel("Ctrl+N", k.pressedCtrlN.Get())),
	)
	__tui_29.AddChild(__tui_32)
	__tui_33 := tui.New(
		tui.WithText(keyLabel("Ctrl+R", k.pressedCtrlR.Get())),
	)
	__tui_29.AddChild(__tui_33)
	__tui_27.AddChild(__tui_29)
	__tui_34 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_35 := tui.New(
		tui.WithText(keyLabel("Ctrl+S", k.pressedCtrlS.Get())),
	)
	__tui_34.AddChild(__tui_35)
	__tui_36 := tui.New(
		tui.WithText(keyLabel("Ctrl+W", k.pressedCtrlW.Get())),
	)
	__tui_34.AddChild(__tui_36)
	__tui_37 := tui.New(
		tui.WithText(keyLabel("Ctrl+X", k.pressedCtrlX.Get())),
	)
	__tui_34.AddChild(__tui_37)
	__tui_38 := tui.New(
		tui.WithText(keyLabel("Ctrl+Z", k.pressedCtrlZ.Get())),
	)
	__tui_34.AddChild(__tui_38)
	__tui_27.AddChild(__tui_34)
	__tui_9.AddChild(__tui_27)
	__tui_0.AddChild(__tui_9)
	__tui_39 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_39)
	__tui_40 := tui.New(
		tui.WithText("Press any key to see it displayed above"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_40)
	__tui_41 := tui.New(
		tui.WithText("Press q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_41)

	return __tui_0
}

func (k *keyboardApp) BindApp(app *tui.App) {
	if k.lastKey != nil {
		k.lastKey.BindApp(app)
	}
	if k.keyCount != nil {
		k.keyCount.BindApp(app)
	}
	if k.pressedEnter != nil {
		k.pressedEnter.BindApp(app)
	}
	if k.pressedTab != nil {
		k.pressedTab.BindApp(app)
	}
	if k.pressedBksp != nil {
		k.pressedBksp.BindApp(app)
	}
	if k.pressedDel != nil {
		k.pressedDel.BindApp(app)
	}
	if k.pressedUp != nil {
		k.pressedUp.BindApp(app)
	}
	if k.pressedDown != nil {
		k.pressedDown.BindApp(app)
	}
	if k.pressedLeft != nil {
		k.pressedLeft.BindApp(app)
	}
	if k.pressedRight != nil {
		k.pressedRight.BindApp(app)
	}
	if k.pressedHome != nil {
		k.pressedHome.BindApp(app)
	}
	if k.pressedEnd != nil {
		k.pressedEnd.BindApp(app)
	}
	if k.pressedPgUp != nil {
		k.pressedPgUp.BindApp(app)
	}
	if k.pressedPgDn != nil {
		k.pressedPgDn.BindApp(app)
	}
	if k.pressedCtrlA != nil {
		k.pressedCtrlA.BindApp(app)
	}
	if k.pressedCtrlD != nil {
		k.pressedCtrlD.BindApp(app)
	}
	if k.pressedCtrlN != nil {
		k.pressedCtrlN.BindApp(app)
	}
	if k.pressedCtrlR != nil {
		k.pressedCtrlR.BindApp(app)
	}
	if k.pressedCtrlS != nil {
		k.pressedCtrlS.BindApp(app)
	}
	if k.pressedCtrlW != nil {
		k.pressedCtrlW.BindApp(app)
	}
	if k.pressedCtrlX != nil {
		k.pressedCtrlX.BindApp(app)
	}
	if k.pressedCtrlZ != nil {
		k.pressedCtrlZ.BindApp(app)
	}
}

var _ tui.AppBinder = (*keyboardApp)(nil)
