// Code generated by tui generate. DO NOT EDIT.
// Source: scrolling.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type scrollingApp struct {
	scrollY *tui.State[int]
	content *tui.Ref
	logs    []logEntry
}

type logEntry struct {
	time    string
	level   string
	message string
}

func Scrolling() *scrollingApp {
	logs := generateLogs()
	return &scrollingApp{
		scrollY: tui.NewState(0),
		content: tui.NewRef(),
		logs:    logs,
	}
}

func generateLogs() []logEntry {
	entries := []logEntry{
		{"12:00:01", "INFO", "Application started"},
		{"12:00:02", "DEBUG", "Loading configuration..."},
		{"12:00:03", "INFO", "Database connected"},
		{"12:00:04", "WARN", "Cache miss on key \"user:42\""},
		{"12:00:05", "ERROR", "Connection timeout: redis:6379"},
		{"12:00:06", "INFO", "Retry succeeded"},
		{"12:00:07", "DEBUG", "Processing batch 1/10"},
		{"12:00:08", "INFO", "Batch complete: 150 records"},
		{"12:00:09", "DEBUG", "Compacting log segments"},
		{"12:00:10", "INFO", "Health check passed"},
		{"12:00:11", "WARN", "Disk usage at 78%"},
		{"12:00:12", "INFO", "Scaling up to 3 replicas"},
		{"12:00:13", "DEBUG", "Syncing state to followers"},
		{"12:00:14", "INFO", "Replica 2 online"},
		{"12:00:15", "INFO", "Replica 3 online"},
		{"12:00:16", "ERROR", "Rate limit exceeded for client 10.0.0.5"},
		{"12:00:17", "WARN", "Memory usage at 85%"},
		{"12:00:18", "INFO", "GC completed: freed 120MB"},
		{"12:00:19", "DEBUG", "Processing batch 2/10"},
		{"12:00:20", "INFO", "Batch complete: 142 records"},
		{"12:00:21", "INFO", "Deploying version v1.2.4"},
		{"12:00:22", "DEBUG", "Rolling update: 1/3 pods"},
		{"12:00:23", "DEBUG", "Rolling update: 2/3 pods"},
		{"12:00:24", "DEBUG", "Rolling update: 3/3 pods"},
		{"12:00:25", "INFO", "Deploy complete: v1.2.4"},
		{"12:00:26", "WARN", "Deprecated API call from service-b"},
		{"12:00:27", "INFO", "Certificate renewed: *.example.com"},
		{"12:00:28", "DEBUG", "Processing batch 3/10"},
		{"12:00:29", "INFO", "Batch complete: 167 records"},
		{"12:00:30", "ERROR", "DNS resolution failed: api.ext.io"},
		{"12:00:31", "INFO", "Fallback to cached DNS record"},
		{"12:00:32", "INFO", "External API call succeeded"},
		{"12:00:33", "DEBUG", "Processing batch 4/10"},
		{"12:00:34", "INFO", "Batch complete: 131 records"},
		{"12:00:35", "WARN", "Slow query: 2.3s on users table"},
		{"12:00:36", "INFO", "Query plan optimized"},
		{"12:00:37", "DEBUG", "Processing batch 5/10"},
		{"12:00:38", "INFO", "Batch complete: 155 records"},
		{"12:00:39", "INFO", "Metrics exported to Prometheus"},
		{"12:00:40", "DEBUG", "Processing batch 6/10"},
		{"12:00:41", "INFO", "Batch complete: 143 records"},
		{"12:00:42", "WARN", "Connection pool near capacity: 45/50"},
		{"12:00:43", "INFO", "Pool expanded to 75 connections"},
		{"12:00:44", "DEBUG", "Processing batch 7/10"},
		{"12:00:45", "INFO", "Batch complete: 168 records"},
		{"12:00:46", "ERROR", "Webhook delivery failed: endpoint down"},
		{"12:00:47", "INFO", "Queued webhook for retry"},
		{"12:00:48", "DEBUG", "Processing batch 8/10"},
		{"12:00:49", "INFO", "Batch complete: 139 records"},
		{"12:00:50", "INFO", "All batches processed successfully"},
	}
	return entries
}

func logLevelColor(level string) string {
	switch level {
	case "INFO":
		return "text-cyan"
	case "DEBUG":
		return "font-dim"
	case "WARN":
		return "text-yellow"
	case "ERROR":
		return "text-red font-bold"
	default:
		return ""
	}
}

func (s *scrollingApp) scrollBy(delta int) {
	el := s.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := s.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	s.scrollY.Set(newY)
}

func (s *scrollingApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { s.scrollBy(1) }),
		tui.OnRune('k', func(ke tui.KeyEvent) { s.scrollBy(-1) }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { s.scrollBy(1) }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { s.scrollBy(-1) }),
		tui.OnKey(tui.KeyPageDown, func(ke tui.KeyEvent) { s.scrollBy(10) }),
		tui.OnKey(tui.KeyPageUp, func(ke tui.KeyEvent) { s.scrollBy(-10) }),
		tui.OnKey(tui.KeyHome, func(ke tui.KeyEvent) { s.scrollY.Set(0) }),
		tui.OnKey(tui.KeyEnd, func(ke tui.KeyEvent) {
			el := s.content.El()
			if el != nil {
				_, maxY := el.MaxScroll()
				s.scrollY.Set(maxY)
			}
		}),
	}
}

func (s *scrollingApp) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		s.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		s.scrollBy(1)
		return true
	}
	return false
}

func (s *scrollingApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(1),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
	)
	__tui_2 := tui.New(
		tui.WithText("System Log"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(fmt.Sprintf("%d entries", len(s.logs))),
		tui.WithMinWidth(0),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, s.scrollY.Get()),
	)
	s.content.Set(__tui_4)
	for __idx_0, entry := range s.logs {
		_ = __idx_0
		__tui_5 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_6 := tui.New(
			tui.WithText(entry.time),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_5.AddChild(__tui_6)
		__tui_7 := tui.New(
			tui.WithText(fmt.Sprintf("%-5s", entry.level)),
		)
		__tui_5.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText(entry.message),
		)
		__tui_5.AddChild(__tui_8)
		__tui_4.AddChild(__tui_5)
	}
	__tui_0.AddChild(__tui_4)
	__tui_9 := tui.New(
		tui.WithText("j/k scroll|PgUp/PgDn page|Home/End jump|q quit"),
		tui.WithFlexShrink(0),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_9)

	return __tui_0
}

func (s *scrollingApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*scrollingApp)
	if !ok {
		return
	}
	s.logs = f.logs
}

var _ tui.PropsUpdater = (*scrollingApp)(nil)

func (s *scrollingApp) BindApp(app *tui.App) {
	if s.scrollY != nil {
		s.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*scrollingApp)(nil)
