// Code generated by tui generate. DO NOT EDIT.
// Source: feed.gsx

package main

import (
	"fmt"
	"math"

	tui "github.com/grindlemire/go-tui"
)

type feedApp struct {
	messages      *tui.State[[]string]
	paused        *tui.State[bool]
	scrollY       *tui.State[int]
	stickToBottom *tui.State[bool]
	content       *tui.Ref
	mode          string
}

func NewFeedApp(mode string) *feedApp {
	return &feedApp{
		messages:      tui.NewState([]string{}),
		paused:        tui.NewState(false),
		scrollY:       tui.NewState(0),
		stickToBottom: tui.NewState(true),
		content:       tui.NewRef(),
		mode:          mode,
	}
}

func (f *feedApp) scrollBy(delta int) {
	el := f.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := f.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	f.scrollY.Set(newY)
	f.stickToBottom.Set(newY >= maxY)
}

func (f *feedApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnStop(tui.Rune('p'), func(ke tui.KeyEvent) {
			f.paused.Set(!f.paused.Get())
		}),
		tui.On(tui.Rune('j'), func(ke tui.KeyEvent) { f.scrollBy(1) }),
		tui.On(tui.Rune('k'), func(ke tui.KeyEvent) { f.scrollBy(-1) }),
		tui.On(tui.KeyUp, func(ke tui.KeyEvent) { f.scrollBy(-1) }),
		tui.On(tui.KeyDown, func(ke tui.KeyEvent) { f.scrollBy(1) }),
		tui.On(tui.KeyPageUp, func(ke tui.KeyEvent) { f.scrollBy(-10) }),
		tui.On(tui.KeyPageDown, func(ke tui.KeyEvent) { f.scrollBy(10) }),
		tui.On(tui.KeyHome, func(ke tui.KeyEvent) {
			f.scrollY.Set(0)
			f.stickToBottom.Set(false)
		}),
		tui.On(tui.KeyEnd, func(ke tui.KeyEvent) {
			f.scrollY.Set(math.MaxInt)
			f.stickToBottom.Set(true)
		}),
	}
}

func (f *feedApp) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		f.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		f.scrollBy(1)
		return true
	}
	return false
}

func (f *feedApp) AddMessage(msg string) {
	f.messages.Update(func(msgs []string) []string {
		return append(msgs, msg)
	})
	if f.stickToBottom.Get() {
		f.scrollY.Set(math.MaxInt)
	}
}

func (f *feedApp) IsPaused() bool {
	return f.paused.Get()
}

func pauseLabel(paused bool) string {
	if paused {
		return "PAUSED"
	}
	return "LIVE"
}

func pauseClass(paused bool) string {
	if paused {
		return "text-yellow font-bold"
	}
	return "text-green font-bold"
}

func (f *feedApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_2 := tui.New(
		tui.WithText("Event Loop Demo"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_4 := tui.New(
		tui.WithText("mode:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(f.mode),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_3.AddChild(__tui_5)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_6 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithPadding(1),
		tui.WithMinHeight(0),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, f.scrollY.Get()),
	)
	f.content.Set(__tui_7)
	for __idx_0, msg := range f.messages.Get() {
		_ = __idx_0
		__tui_8 := tui.New(
			tui.WithText(msg),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_7.AddChild(__tui_8)
	}
	__tui_0.AddChild(__tui_7)
	__tui_9 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_11 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_12 := tui.New(
		tui.WithText("p: toggle"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_12)
	__tui_13 := tui.New(
		tui.WithText("j/k: scroll"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_13)
	__tui_14 := tui.New(
		tui.WithText("q: quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_11.AddChild(__tui_14)
	__tui_10.AddChild(__tui_11)
	__tui_15 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_16 := tui.New(
		tui.WithText(pauseLabel(f.paused.Get())),
	)
	__tui_15.AddChild(__tui_16)
	__tui_17 := tui.New(
		tui.WithText(fmt.Sprintf("%d msgs", len(f.messages.Get()))),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_15.AddChild(__tui_17)
	__tui_10.AddChild(__tui_15)
	__tui_0.AddChild(__tui_10)

	return __tui_0
}

func (f *feedApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*feedApp)
	if !ok {
		return
	}
	f.mode = f.mode
}

var _ tui.PropsUpdater = (*feedApp)(nil)

func (f *feedApp) BindApp(app *tui.App) {
	if f.messages != nil {
		f.messages.BindApp(app)
	}
	if f.paused != nil {
		f.paused.BindApp(app)
	}
	if f.scrollY != nil {
		f.scrollY.BindApp(app)
	}
	if f.stickToBottom != nil {
		f.stickToBottom.BindApp(app)
	}
}

var _ tui.AppBinder = (*feedApp)(nil)
