// Code generated by tui generate. DO NOT EDIT.
// Source: search.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type searchInput struct {
	Active *tui.State[bool]
	Query  *tui.State[string]
}

func SearchInput(active *tui.State[bool], query *tui.State[string]) *searchInput {
	return &searchInput{Active: active, Query: query}
}

func (s *searchInput) KeyMap() tui.KeyMap {
	if !s.Active.Get() {
		return nil
	}
	return tui.KeyMap{
		tui.OnRunesStop(s.appendChar),
		tui.OnKeyStop(tui.KeyBackspace, s.deleteChar),
		tui.OnKeyStop(tui.KeyEnter, s.submit),
		tui.OnKeyStop(tui.KeyEscape, s.deactivate),
	}
}

func (s *searchInput) appendChar(ke tui.KeyEvent) {
	s.Query.Set(s.Query.Get() + string(ke.Rune))
}

func (s *searchInput) deleteChar(ke tui.KeyEvent) {
	q := s.Query.Get()
	if len(q) > 0 {
		s.Query.Set(q[:len(q)-1])
	}
}

func (s *searchInput) submit(ke tui.KeyEvent) {
	s.Active.Set(false)
}

func (s *searchInput) deactivate(ke tui.KeyEvent) {
	s.Active.Set(false)
	s.Query.Set("")
}

func (s *searchInput) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New()
	if s.Active.Get() {
		__tui_1 := tui.New(
			tui.WithBorder(tui.BorderRounded),
			tui.WithPadding(1),
		)
		__tui_2 := tui.New(
			tui.WithText("Search:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(s.Query.Get()),
		)
		__tui_1.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText("|"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_4)
		__tui_0.AddChild(__tui_1)
	}

	return __tui_0
}
