// Code generated by tui generate. DO NOT EDIT.
// Source: inline.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type myApp struct {
	app          *tui.App
	showSettings *tui.State[bool]
	textarea     *tui.TextArea
}

func InlineApp() *myApp {
	a := &myApp{
		showSettings: tui.NewState(false),
	}
	a.textarea = tui.NewTextArea(
		tui.WithTextAreaWidth(60),
		tui.WithTextAreaBorder(tui.BorderRounded),
		tui.WithTextAreaPlaceholder("Type here..."),
		tui.WithTextAreaOnSubmit(a.send),
	)
	return a
}

func (a *myApp) BindApp(app *tui.App) {
	a.app = app
	a.showSettings.BindApp(app)
	a.textarea.BindApp(app)
}

func (a *myApp) send(text string) {
	if text == "" {
		return
	}
	a.textarea.Clear()
	a.app.PrintAboveln("You: %s", text)
}

func (a *myApp) toggleSettings() {
	if a.showSettings.Get() {
		_ = a.app.ExitAlternateScreen()
		a.showSettings.Set(false)
		return
	}
	a.showSettings.Set(true)
	_ = a.app.EnterAlternateScreen()
}

func (a *myApp) KeyMap() tui.KeyMap {
	if a.showSettings.Get() {
		return tui.KeyMap{
			tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { a.toggleSettings() }),
			tui.OnKey(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
		}
	}

	km := a.textarea.KeyMap()
	km = append(km,
		tui.OnKeyStop(tui.KeyCtrlS, func(ke tui.KeyEvent) { a.toggleSettings() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
	)
	return km
}

func (a *myApp) Watchers() []tui.Watcher {
	return a.textarea.Watchers()
}

func (a *myApp) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if a.showSettings.Get() {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithHeightPercent(100.00),
			tui.WithPadding(1),
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_2 := tui.New(
			tui.WithText("Settings"),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText("Press Escape to"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_3)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else {
		__tui_4 := a.textarea.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_4
		}
	}

	return __tui_0
}

func (a *myApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*myApp)
	if !ok {
		return
	}
	a.app = f.app
	a.textarea = f.textarea
}

var _ tui.PropsUpdater = (*myApp)(nil)
