// Code generated by tui generate. DO NOT EDIT.
// Source: elements.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type elementsApp struct {
	progress    *tui.State[int]
	scrollY     *tui.State[int]
	content     *tui.Ref
	name        *tui.State[string]
	note        *tui.State[string]
	selectedBtn *tui.State[string]
	btnRefs     *tui.RefMap[string]
}

var buttonLabels = []string{"Save", "Cancel", "Submit", "Disabled"}

func Elements() *elementsApp {
	return &elementsApp{
		progress:    tui.NewState(62),
		scrollY:     tui.NewState(0),
		content:     tui.NewRef(),
		name:        tui.NewState(""),
		note:        tui.NewState(""),
		selectedBtn: tui.NewState(""),
		btnRefs:     tui.NewRefMap[string](),
	}
}

func (e *elementsApp) onNoteSubmit(text string) {
	e.note.Set(text)
}

func greeting(name string) string {
	if name == "" {
		return "Hello, World!"
	}
	return fmt.Sprintf("Hello, %s!", name)
}

func (e *elementsApp) scrollBy(delta int) {
	el := e.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := e.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	e.scrollY.Set(newY)
}

func (e *elementsApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.KeyTab, func(ke tui.KeyEvent) { ke.App().FocusNext() }),
		tui.On(tui.Rune('n'), func(ke tui.KeyEvent) { e.name.Set("John Doe") }),
		tui.On(tui.KeyTab.Shift(), func(ke tui.KeyEvent) { ke.App().FocusPrev() }),
		tui.On(tui.Rune('+'), func(ke tui.KeyEvent) {
			v := e.progress.Get() + 5
			if v > 100 {
				v = 100
			}
			e.progress.Set(v)
		}),
		tui.On(tui.Rune('-'), func(ke tui.KeyEvent) {
			v := e.progress.Get() - 5
			if v < 0 {
				v = 0
			}
			e.progress.Set(v)
		}),
		tui.On(tui.Rune('j'), func(ke tui.KeyEvent) { e.scrollBy(1) }),
		tui.On(tui.Rune('k'), func(ke tui.KeyEvent) { e.scrollBy(-1) }),
		tui.On(tui.KeyDown, func(ke tui.KeyEvent) { e.scrollBy(1) }),
		tui.On(tui.KeyUp, func(ke tui.KeyEvent) { e.scrollBy(-1) }),
	}
}

func (e *elementsApp) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		e.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		e.scrollBy(1)
		return true
	}

	if me.Button == tui.MouseLeft && me.Action == tui.MousePress {
		for name, el := range e.btnRefs.All() {
			if el != nil && el.ContainsPoint(me.X, me.Y) {
				if name != "Disabled" {
					e.selectedBtn.Set(name)
				}
				return true
			}
		}
	}

	return false
}

func progressBar(value, width int) string {
	filled := value * width / 100
	bar := ""
	for i := 0; i < width; i++ {
		if i < filled {
			bar += "█"
		} else {
			bar += "░"
		}
	}
	return bar
}

func (e *elementsApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithHeightPercent(100.00),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, e.scrollY.Get()),
	)
	e.content.Set(__tui_0)
	__tui_1 := tui.New(
		tui.WithText("Built-in Elements"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_3 := tui.New(
		tui.WithText("Text Elements"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("Paragraph text (<p>) wraps automatically when the content exceeds the available width. This demonstrates how longer text content is displayed."),
	)
	__tui_2.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithHR(),
	)
	__tui_2.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText("This is a <span> element for inline styled text"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_2.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_2.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("<hr> above draws a line, <br> inserts a blank line"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_8)
	__tui_0.AddChild(__tui_2)
	__tui_9 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_11 := tui.New(
		tui.WithText("Lists (<ul> / <li>)"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
	)
	__tui_13 := tui.New()
	__tui_14 := tui.New(
		tui.WithText("First item"),
	)
	__tui_13.AddChild(__tui_14)
	__tui_12.AddChild(__tui_13)
	__tui_15 := tui.New()
	__tui_16 := tui.New(
		tui.WithText("Second item"),
	)
	__tui_15.AddChild(__tui_16)
	__tui_12.AddChild(__tui_15)
	__tui_17 := tui.New()
	__tui_18 := tui.New(
		tui.WithText("Third item"),
	)
	__tui_17.AddChild(__tui_18)
	__tui_12.AddChild(__tui_17)
	__tui_19 := tui.New()
	__tui_20 := tui.New(
		tui.WithText("Fourth (styled)"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_19.AddChild(__tui_20)
	__tui_12.AddChild(__tui_19)
	__tui_10.AddChild(__tui_12)
	__tui_9.AddChild(__tui_10)
	__tui_21 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_22 := tui.New(
		tui.WithText("Table"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_21.AddChild(__tui_22)
	__tui_23 := tui.New(
		tui.WithTag("table"),
		tui.WithDisplay(tui.DisplayFlex),
		tui.WithDirection(tui.Column),
		tui.WithPadding(1),
	)
	__tui_24 := tui.New(
		tui.WithTag("tr"),
		tui.WithDisplay(tui.DisplayFlex),
		tui.WithDirection(tui.Row),
	)
	__tui_25 := tui.New(
		tui.WithTag("th"),
		tui.WithText("Name"),
	)
	__tui_24.AddChild(__tui_25)
	__tui_26 := tui.New(
		tui.WithTag("th"),
		tui.WithText("Role"),
	)
	__tui_24.AddChild(__tui_26)
	__tui_27 := tui.New(
		tui.WithTag("th"),
		tui.WithText("Lvl"),
	)
	__tui_24.AddChild(__tui_27)
	__tui_23.AddChild(__tui_24)
	__tui_28 := tui.New(
		tui.WithHR(),
	)
	__tui_23.AddChild(__tui_28)
	__tui_29 := tui.New(
		tui.WithTag("tr"),
		tui.WithDisplay(tui.DisplayFlex),
		tui.WithDirection(tui.Row),
	)
	__tui_30 := tui.New(
		tui.WithTag("td"),
		tui.WithText("Alice"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_29.AddChild(__tui_30)
	__tui_31 := tui.New(
		tui.WithTag("td"),
		tui.WithText("Engineer"),
	)
	__tui_29.AddChild(__tui_31)
	__tui_32 := tui.New(
		tui.WithTag("td"),
		tui.WithText("Sr"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_29.AddChild(__tui_32)
	__tui_23.AddChild(__tui_29)
	__tui_33 := tui.New(
		tui.WithTag("tr"),
		tui.WithDisplay(tui.DisplayFlex),
		tui.WithDirection(tui.Row),
	)
	__tui_34 := tui.New(
		tui.WithTag("td"),
		tui.WithText("Bob"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_33.AddChild(__tui_34)
	__tui_35 := tui.New(
		tui.WithTag("td"),
		tui.WithText("Designer"),
	)
	__tui_33.AddChild(__tui_35)
	__tui_36 := tui.New(
		tui.WithTag("td"),
		tui.WithText("Jr"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
	)
	__tui_33.AddChild(__tui_36)
	__tui_23.AddChild(__tui_33)
	__tui_21.AddChild(__tui_23)
	__tui_9.AddChild(__tui_21)
	__tui_0.AddChild(__tui_9)
	__tui_37 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_38 := tui.New(
		tui.WithText("Buttons"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_37.AddChild(__tui_38)
	__tui_39 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	for __idx_0, label := range buttonLabels {
		_ = __idx_0
		if label == "Disabled" {
			__tui_40 := tui.New(
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			e.btnRefs.Put(label, __tui_40)
			__tui_41 := tui.New(tui.WithText(label))
			__tui_40.AddChild(__tui_41)
			__tui_39.AddChild(__tui_40)
		} else if label == e.selectedBtn.Get() {
			__tui_42 := tui.New(
				tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
			)
			e.btnRefs.Put(label, __tui_42)
			__tui_43 := tui.New(tui.WithText(label))
			__tui_42.AddChild(__tui_43)
			__tui_39.AddChild(__tui_42)
		} else {
			__tui_44 := tui.New()
			e.btnRefs.Put(label, __tui_44)
			__tui_45 := tui.New(tui.WithText(label))
			__tui_44.AddChild(__tui_45)
			__tui_39.AddChild(__tui_44)
		}
	}
	__tui_37.AddChild(__tui_39)
	__tui_0.AddChild(__tui_37)
	__tui_46 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_47 := tui.New(
		tui.WithText("Input & TextArea"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_46.AddChild(__tui_47)
	__tui_48 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_49 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithWidthPercent(50.00),
	)
	__tui_50 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_51 := tui.New(
		tui.WithText("Name:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_50.AddChild(__tui_51)
	__tui_52 := app.MountPersistent(e, 0, func() tui.Component {
		return tui.NewInput(
			tui.WithInputPlaceholder("Type your name..."),
			tui.WithInputValue(e.name),
			tui.WithInputWidth(30),
			tui.WithInputBorder(tui.BorderRounded),
			tui.WithInputFocusGradient(tui.NewGradient(tui.Cyan, tui.Magenta)),
		)
	})
	__tui_50.AddChild(__tui_52)
	__tui_49.AddChild(__tui_50)
	__tui_53 := tui.New(
		tui.WithText(greeting(e.name.Get())),
		tui.WithWidth(30),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_49.AddChild(__tui_53)
	__tui_48.AddChild(__tui_49)
	__tui_54 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithWidthPercent(50.00),
	)
	__tui_55 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_56 := tui.New(
		tui.WithText("Note:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_55.AddChild(__tui_56)
	__tui_57 := app.MountPersistent(e, 1, func() tui.Component {
		return tui.NewTextArea(
			tui.WithTextAreaPlaceholder("Write a note..."),
			tui.WithTextAreaWidth(30),
			tui.WithTextAreaMaxHeight(4),
			tui.WithTextAreaBorder(tui.BorderRounded),
			tui.WithTextAreaOnSubmit(e.onNoteSubmit),
			tui.WithTextAreaFocusColor(tui.BrightRed),
		)
	})
	__tui_55.AddChild(__tui_57)
	__tui_54.AddChild(__tui_55)
	if e.note.Get() != "" {
		__tui_58 := tui.New(
			tui.WithText(fmt.Sprintf("Saved: %s", e.note.Get())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_54.AddChild(__tui_58)
	}
	__tui_48.AddChild(__tui_54)
	__tui_46.AddChild(__tui_48)
	__tui_59 := tui.New(
		tui.WithText("Tab to cycle focus | Esc to blur | Enter submits note"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_46.AddChild(__tui_59)
	__tui_0.AddChild(__tui_46)
	__tui_60 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_61 := tui.New(
		tui.WithText("Progress Bars"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_60.AddChild(__tui_61)
	__tui_62 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_63 := tui.New(
		tui.WithText("Download:"),
		tui.WithWidth(10),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_62.AddChild(__tui_63)
	__tui_64 := tui.New(
		tui.WithText(progressBar(e.progress.Get(), 25)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_62.AddChild(__tui_64)
	__tui_65 := tui.New(
		tui.WithText(fmt.Sprintf("%d%%", e.progress.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_62.AddChild(__tui_65)
	__tui_60.AddChild(__tui_62)
	__tui_66 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_67 := tui.New(
		tui.WithText("Upload:"),
		tui.WithWidth(10),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_66.AddChild(__tui_67)
	__tui_68 := tui.New(
		tui.WithText(progressBar(100, 25)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_66.AddChild(__tui_68)
	__tui_69 := tui.New(
		tui.WithText("100%"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_66.AddChild(__tui_69)
	__tui_60.AddChild(__tui_66)
	__tui_70 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(2),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_71 := tui.New(
		tui.WithText("Build:"),
		tui.WithWidth(10),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_70.AddChild(__tui_71)
	__tui_72 := tui.New(
		tui.WithText(progressBar(35, 25)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
	)
	__tui_70.AddChild(__tui_72)
	__tui_73 := tui.New(
		tui.WithText("35%"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
	)
	__tui_70.AddChild(__tui_73)
	__tui_60.AddChild(__tui_70)
	__tui_0.AddChild(__tui_60)
	__tui_74 := tui.New(
		tui.WithText("tab focus input | +/- progress | j/k scroll | q quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_74)

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (e *elementsApp) bindAppFields(app *tui.App) {
	if e.progress != nil {
		e.progress.BindApp(app)
	}
	if e.scrollY != nil {
		e.scrollY.BindApp(app)
	}
	if e.name != nil {
		e.name.BindApp(app)
	}
	if e.note != nil {
		e.note.BindApp(app)
	}
	if e.selectedBtn != nil {
		e.selectedBtn.BindApp(app)
	}
}

func (e *elementsApp) BindApp(app *tui.App) {
	e.bindAppFields(app)
}

var _ tui.AppBinder = (*elementsApp)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener   = (*elementsApp)(nil)
	_ tui.MouseListener = (*elementsApp)(nil)
)
