package tuigen

import (
	"strings"
	"testing"
)

func TestGenerator_SimpleComponent(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"empty component": {
			input: `package x
templ Empty() {
}`,
			wantContains: []string{
				"type EmptyView struct",
				"Root",
				"*tui.Element",
				"watchers",
				"[]tui.Watcher",
				"func Empty() *EmptyView",
				"var view EmptyView",
				"var watchers []tui.Watcher",
				"return &view",
			},
		},
		"component with single element": {
			input: `package x
templ Header() {
	<div></div>
}`,
			wantContains: []string{
				"type HeaderView struct",
				"func Header() *HeaderView",
				"__tui_0 := tui.New()",
				"Root:      __tui_0",
			},
		},
		"component with params": {
			input: `package x
templ Greeting(name string, count int) {
	<span>Hello</span>
}`,
			wantContains: []string{
				"func Greeting(name string, count int) *GreetingView",
				"type GreetingView struct",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_NestedElements(t *testing.T) {
	input := `package x
templ Layout() {
	<div>
		<div>
			<span>nested</span>
		</div>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Should have 3 element variables
	if !strings.Contains(code, "__tui_0 := tui.New()") {
		t.Error("missing outer box element")
	}

	// Should have AddChild calls
	if !strings.Contains(code, ".AddChild(") {
		t.Error("missing AddChild call")
	}

	// Should return view struct with Root set to outer element
	if !strings.Contains(code, "Root:      __tui_0") {
		t.Error("missing Root assignment to outer element")
	}

	if !strings.Contains(code, "return &view") {
		t.Error("missing return view statement")
	}
}

func TestGenerator_TopLevelGoFunc(t *testing.T) {
	input := `package x

func helper(x int) int {
	return x * 2
}

templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "func helper(x int) int") {
		t.Errorf("missing helper function\nGot:\n%s", code)
	}

	if !strings.Contains(code, "return x * 2") {
		t.Errorf("missing helper function body\nGot:\n%s", code)
	}
}

func TestGenerator_ImportPropagation(t *testing.T) {
	input := `package x
import (
	"fmt"
	tui "github.com/grindlemire/go-tui"
)

templ Test() {
	<div direction={tui.Column}>
		<span>{fmt.Sprintf("hello")}</span>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Original imports should be preserved
	if !strings.Contains(code, `"fmt"`) {
		t.Error("missing fmt import")
	}

	if !strings.Contains(code, `"github.com/grindlemire/go-tui"`) {
		t.Error("missing tui root import")
	}
}

func TestGenerator_Header(t *testing.T) {
	input := `package x
templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "Code generated by tui generate. DO NOT EDIT.") {
		t.Error("missing DO NOT EDIT header")
	}

	if !strings.Contains(code, "Source: test.gsx") {
		t.Error("missing source file comment")
	}
}

func TestGenerator_MethodComponent(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"method templ generates method Render returning Element": {
			input: `package x

type sidebar struct{}

templ (s *sidebar) Render() {
	<div></div>
}`,
			wantContains: []string{
				"func (s *sidebar) Render(app *tui.App) *tui.Element {",
				"__tui_0 := tui.New()",
				"return __tui_0",
			},
			wantNotContains: []string{
				"View struct",
				"var view",
				"var watchers",
				"return &view",
			},
		},
		"method templ with nested elements": {
			input: `package x

type panel struct{}

templ (p *panel) Render() {
	<div class="flex-col">
		<span>hello</span>
	</div>
}`,
			wantContains: []string{
				"func (p *panel) Render(app *tui.App) *tui.Element {",
				"__tui_0 := tui.New(",
				"return __tui_0",
			},
			wantNotContains: []string{
				"PanelView",
				"var view",
			},
		},
		"method templ with struct mount": {
			input: `package x

type myApp struct{}

templ (a *myApp) Render() {
	<div>
		@Sidebar()
	</div>
}`,
			wantContains: []string{
				"func (a *myApp) Render(app *tui.App) *tui.Element {",
				"app.Mount(a, 0, func() tui.Component {",
				"return Sidebar()",
				"})",
				"__tui_0.AddChild(",
				"return __tui_0",
			},
			wantNotContains: []string{
				".Root",
				"var view",
			},
		},
		"mount indices increment for multiple mounts": {
			input: `package x

type myApp struct{}

templ (a *myApp) Render() {
	<div>
		@First()
		@Second()
		@Third()
	</div>
}`,
			wantContains: []string{
				"app.Mount(a, 0, func() tui.Component {",
				"return First()",
				"app.Mount(a, 1, func() tui.Component {",
				"return Second()",
				"app.Mount(a, 2, func() tui.Component {",
				"return Third()",
			},
		},
		"struct mount with args": {
			input: `package x

type myApp struct{}

templ (a *myApp) Render() {
	<div>
		@Sidebar(a.query)
		@SearchInput(a.active, a.query)
	</div>
}`,
			wantContains: []string{
				"app.Mount(a, 0, func() tui.Component {",
				"return Sidebar(a.query)",
				"app.Mount(a, 1, func() tui.Component {",
				"return SearchInput(a.active, a.query)",
			},
		},
		"method templ with conditional": {
			input: `package x

type sidebar struct{}

templ (s *sidebar) Render() {
	if true {
		<div><span>visible</span></div>
	}
}`,
			wantContains: []string{
				"func (s *sidebar) Render(app *tui.App) *tui.Element {",
				"if true {",
			},
		},
		"empty method templ returns nil": {
			input: `package x

type empty struct{}

templ (e *empty) Render() {
}`,
			wantContains: []string{
				"func (e *empty) Render(app *tui.App) *tui.Element {",
				"return nil",
			},
		},
		"method templ with children slot uses receiver field": {
			input: `package x

type card struct {
	title    string
	children []*tui.Element
}

templ (c *card) Render() {
	<div>
		<span>{c.title}</span>
		{children...}
	</div>
}`,
			wantContains: []string{
				"for _, __child := range c.children {",
			},
			wantNotContains: []string{
				"range children {",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_FunctionTemplChildrenSlotUsesBareChildren(t *testing.T) {
	input := `package x

templ Card(title string) {
	<div>
		<span>{title}</span>
		{children...}
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)
	if !strings.Contains(code, "for _, __child := range children {") {
		t.Errorf("function templ should use bare 'children' parameter\nGot:\n%s", code)
	}
}

func TestGenerator_FunctionComponentCallUnchanged(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"function templ with component call uses view struct pattern": {
			input: `package x

templ Parent() {
	<div>
		@Header("title")
	</div>
}`,
			wantContains: []string{
				"func Parent() *ParentView",
				"type ParentView struct",
				`__tui_1 := Header("title")`,
				"__tui_0.AddChild(__tui_1.Root)",
				"return &view",
			},
			wantNotContains: []string{
				"tui.Mount",
				"func() tui.Component", // no mount factory closure
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_VerbatimPassthrough(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"type definition passes through": {
			input: `package x

type sidebar struct {
	Query    string
	expanded bool
}

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				"type sidebar struct",
				"Query    string",
				"expanded bool",
				"func Header() *HeaderView",
			},
		},
		"constructor method passes through": {
			input: `package x

func (s *sidebar) toggle() {
	s.expanded = !s.expanded
}

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				"func (s *sidebar) toggle()",
				"s.expanded = !s.expanded",
			},
		},
		"simple var declaration passes through": {
			input: `package x

var defaultName = "hello"

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				`var defaultName = "hello"`,
			},
		},
		"const declaration passes through": {
			input: `package x

const maxItems = 10

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				"const maxItems = 10",
			},
		},
		"mixed file with type constructor method and templ": {
			input: `package x

type sidebar struct {
	expanded bool
}

func NewSidebar() *sidebar {
	return &sidebar{expanded: true}
}

func (s *sidebar) toggle() {
	s.expanded = !s.expanded
}

templ (s *sidebar) Render() {
	<div><span>sidebar</span></div>
}`,
			wantContains: []string{
				"type sidebar struct",
				"expanded bool",
				"func NewSidebar() *sidebar",
				"return &sidebar{expanded: true}",
				"func (s *sidebar) toggle()",
				"s.expanded = !s.expanded",
				"func (s *sidebar) Render(app *tui.App) *tui.Element",
				"return __tui_0",
			},
			wantNotContains: []string{
				"RenderView",
				"var view",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_ReactiveIf(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"reactive if with single state var": {
			input: `package x
templ Toggle() {
	count := tui.NewState(0)
	<div>
		if count.Get() == 0 {
			<span>{"zero"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				"__tui_0.AddChild(__cond_0)",
				"__update___cond_0 := func()",
				"__cond_0.RemoveAllChildren()",
				"if count.Get() == 0",
				"__update___cond_0()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
			},
		},
		"reactive if/else": {
			input: `package x
templ Toggle() {
	count := tui.NewState(0)
	<div>
		if count.Get() >= 5 {
			<span>{"high"}</span>
		} else {
			<span>{"low"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				"__update___cond_0 := func()",
				"__cond_0.RemoveAllChildren()",
				"if count.Get() >= 5",
				"} else {",
				"__update___cond_0()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
			},
		},
		"non-reactive if stays plain": {
			input: `package x
templ Static(show bool) {
	<div>
		if show {
			<span>{"visible"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"if show {",
			},
			wantNotContains: []string{
				"__cond_",
				"RemoveAllChildren",
			},
		},
		"for loop with state in body becomes reactive": {
			input: `package x
templ LoopCond(items []string) {
	count := tui.NewState(0)
	<div>
		for _, item := range items {
			if count.Get() > 0 {
				<span>{item}</span>
			}
		}
	</div>
}`,
			wantContains: []string{
				"__loop_0_style := __tui_0.LayoutStyle()",
				"__loop_0 := tui.New(tui.WithDirection(__loop_0_style.Direction), tui.WithGap(__loop_0_style.Gap))",
				"RemoveAllChildren",
				"__update___loop_0 := func()",
				"__update___loop_0()",
				`count.Bind(func(_ int) { __update___loop_0() })`,
			},
			wantNotContains: []string{
				"__cond_", // if inside for stays non-reactive
			},
		},
		"for loop without state stays plain": {
			input: `package x
templ PlainLoop(items []string) {
	<div>
		for _, item := range items {
			<span>{item}</span>
		}
	</div>
}`,
			wantNotContains: []string{
				"__loop_",
				"__cond_",
				"RemoveAllChildren",
			},
		},
		"state in body also triggers binding": {
			input: `package x
import "fmt"
templ Multi() {
	count := tui.NewState(0)
	name := tui.NewState("hello")
	<div>
		if count.Get() > 0 {
			<span>{fmt.Sprintf("%s: %d", name.Get(), count.Get())}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
				`name.Bind(func(_ string) { __update___cond_0() })`,
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_MethodComponent_TopLevelIfProducesRoot(t *testing.T) {
	input := `package x
type panel struct {
	show *tui.State[bool]
}

templ (p *panel) Render() {
	if p.show.Get() {
		<span>{"on"}</span>
	} else {
		<span>{"off"}</span>
	}
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)
	want := []string{
		"func (p *panel) Render(app *tui.App) *tui.Element {",
		"var __tui_0 *tui.Element",
		"if p.show.Get() {",
		"if __tui_0 == nil {",
		"__tui_0 = __tui_1",
		"__tui_0 = __tui_2",
		"return __tui_0",
	}
	for _, s := range want {
		if !strings.Contains(code, s) {
			t.Errorf("output missing expected string: %q\nGot:\n%s", s, code)
		}
	}

	if strings.Contains(code, "return nil") {
		t.Errorf("output contains unexpected return nil\nGot:\n%s", code)
	}
}

func TestGenerator_TextareaElement(t *testing.T) {
	type tc struct {
		input        string
		wantContains []string
	}

	tests := map[string]tc{
		"textarea generates mount with NewTextArea": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea placeholder="Type here..." width={40} />
}`,
			wantContains: []string{
				"app.MountPersistent(",
				"tui.NewTextArea(",
				`tui.WithTextAreaPlaceholder("Type here...")`,
				"tui.WithTextAreaWidth(40)",
			},
		},
		"textarea with onSubmit handler": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea onSubmit={c.handleSubmit} />
}`,
			wantContains: []string{
				"tui.NewTextArea(",
				"tui.WithTextAreaOnSubmit(c.handleSubmit)",
			},
		},
		"textarea with border": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea border={tui.BorderRounded} />
}`,
			wantContains: []string{
				"tui.NewTextArea(",
				"tui.WithTextAreaBorder(tui.BorderRounded)",
			},
		},
		"textarea with no options": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea />
}`,
			wantContains: []string{
				"app.MountPersistent(",
				"tui.NewTextArea()",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing %q.\nGot:\n%s", want, code)
				}
			}
		})
	}
}

func TestGenerator_InterfaceChecks(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"KeyMap method emits KeyListener check": {
			input: `package x

type counter struct{}

templ (c *counter) Render() {
	<div>hello</div>
}

func (c *counter) KeyMap() tui.KeyMap {
	return nil
}`,
			wantContains: []string{
				"_ tui.KeyListener = (*counter)(nil)",
			},
		},
		"HandleMouse method emits MouseListener check": {
			input: `package x

type clicker struct{}

templ (c *clicker) Render() {
	<div>hello</div>
}

func (c *clicker) HandleMouse(me tui.MouseEvent) bool {
	return false
}`,
			wantContains: []string{
				"_ tui.MouseListener = (*clicker)(nil)",
			},
		},
		"Init method emits Initializer check": {
			input: `package x

type loader struct{}

templ (l *loader) Render() {
	<div>hello</div>
}

func (l *loader) Init() func() {
	return nil
}`,
			wantContains: []string{
				"_ tui.Initializer = (*loader)(nil)",
			},
		},
		"Watchers method emits WatcherProvider check": {
			input: `package x

type ticker struct{}

templ (t *ticker) Render() {
	<div>hello</div>
}

func (t *ticker) Watchers() []tui.Watcher {
	return nil
}`,
			wantContains: []string{
				"_ tui.WatcherProvider = (*ticker)(nil)",
			},
		},
		"multiple interfaces on same type": {
			input: `package x

type app struct{}

templ (a *app) Render() {
	<div>hello</div>
}

func (a *app) KeyMap() tui.KeyMap {
	return nil
}

func (a *app) Init() func() {
	return nil
}`,
			wantContains: []string{
				"_ tui.KeyListener = (*app)(nil)",
				"_ tui.Initializer = (*app)(nil)",
			},
		},
		"no checks for function components": {
			input: `package x

templ Header() {
	<div>hello</div>
}

func helper() {}`,
			wantNotContains: []string{
				"Compile-time interface",
			},
		},
		"no checks for non-component receiver types": {
			input: `package x

type helper struct{}

templ Header() {
	<div>hello</div>
}

func (h *helper) KeyMap() tui.KeyMap {
	return nil
}`,
			wantNotContains: []string{
				"_ tui.KeyListener",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_ConditionalComponentCallScoping(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"component call inside if block hoists var and nil-guards wiring": {
			input: `package x

templ ItemRow(hasBadge bool) {
	<div>
		<span>name</span>
		if hasBadge {
			@Badge()
		}
	</div>
}`,
			wantContains: []string{
				// Hoisted declaration at function scope
				"var __tui_2 *BadgeView",
				// Assignment (not short declaration) inside the if block
				"__tui_2 = Badge()",
				// Nil-guarded watcher aggregation
				"if __tui_2 != nil {\n\t\twatchers = append(watchers, __tui_2.GetWatchers()...)\n\t}",
				// Nil-guarded bindApp (3 tabs: function body > closure body > nil guard)
				"if __tui_2 != nil {\n\t\t\tif binder, ok := any(__tui_2).(tui.AppBinder)",
				// Nil-guarded unbindApp
				"if __tui_2 != nil {\n\t\t\tif unbinder, ok := any(__tui_2).(tui.AppUnbinder)",
			},
			wantNotContains: []string{
				// Must NOT have short declaration inside the if block
				"__tui_2 := Badge()",
			},
		},
		"unconditional component call is unchanged": {
			input: `package x

templ Parent() {
	<div>
		@Header()
	</div>
}`,
			wantContains: []string{
				"__tui_1 := Header()",
				"watchers = append(watchers, __tui_1.GetWatchers()...)",
			},
			wantNotContains: []string{
				"var __tui_1",
				"if __tui_1 != nil",
			},
		},
		"mixed conditional and unconditional component calls": {
			input: `package x

templ Mixed(show bool) {
	<div>
		@Header()
		if show {
			@Badge()
		}
	</div>
}`,
			wantContains: []string{
				// Header is unconditional
				"__tui_1 := Header()",
				// Badge is conditional — hoisted
				"var __tui_2 *BadgeView",
				"__tui_2 = Badge()",
				// Header watcher is direct
				"watchers = append(watchers, __tui_1.GetWatchers()...)",
				// Badge watcher is nil-guarded
				"if __tui_2 != nil {\n\t\twatchers = append(watchers, __tui_2.GetWatchers()...)\n\t}",
			},
		},
		"component calls in both if and else branches": {
			input: `package x

templ Row(a bool) {
	<div>
		if a {
			@Badge()
		} else {
			@Icon()
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1 *BadgeView",
				"var __tui_2 *IconView",
				"__tui_1 = Badge()",
				"__tui_2 = Icon()",
				"if __tui_1 != nil",
				"if __tui_2 != nil",
			},
			wantNotContains: []string{
				"__tui_1 := Badge()",
				"__tui_2 := Icon()",
			},
		},
		"nested conditional component call": {
			input: `package x

templ Nested(a bool, b bool) {
	<div>
		if a {
			if b {
				@Badge()
			}
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1 *BadgeView",
				"__tui_1 = Badge()",
				"if __tui_1 != nil",
			},
			wantNotContains: []string{
				"__tui_1 := Badge()",
			},
		},
		"component call in children-building if block": {
			input: `package x

templ Outer(show bool) {
	<div>
		@Wrapper() {
			if show {
				@Badge()
			}
		}
	</div>
}`,
			wantContains: []string{
				// __tui_3 because __tui_2 is consumed by the children slice variable
				"var __tui_3 *BadgeView",
				"__tui_3 = Badge()",
				"if __tui_3 != nil",
			},
			wantNotContains: []string{
				"__tui_3 := Badge()",
			},
		},
		"component call inside for loop hoists var": {
			input: `package x

templ List(items []string) {
	<div>
		for _, item := range items {
			@Badge(item)
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1 *BadgeView",
				"__tui_1 = Badge(item)",
				"if __tui_1 != nil",
			},
			wantNotContains: []string{
				"__tui_1 := Badge(item)",
			},
		},
		"method templ with conditional function templ uses short declaration": {
			input: `package x

type sidebar struct{}

templ Foo() {
	<div></div>
}

templ (s *sidebar) Render() {
	<div>
		if true {
			@Foo()
		}
	</div>
}`,
			wantContains: []string{
				// Method templs don't hoist - they use := inside the block
				"__tui_1 := Foo()",
			},
			wantNotContains: []string{
				// No hoisted var declaration
				"var __tui_1",
				// No bare assignment
				"__tui_1 = Foo()",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}
