// Code generated by tui generate. DO NOT EDIT.
// Source: streaming.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

func tickElapsed(elapsed *tui.State[int]) func() {
	return func() {
		elapsed.Set(elapsed.Get() + 1)
	}
}

func addLine(lineCount *tui.State[int], content *tui.Ref) func(string) {
	return func(line string) {
		lineCount.Set(lineCount.Get() + 1)

		el := content.El()
		stayAtBottom := el.IsAtBottom()

		lineElem := tui.New(
			tui.WithText(line),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		el.AddChild(lineElem)

		if stayAtBottom {
			el.ScrollToBottom()
		}
	}
}

type StreamAppView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	Content  *tui.Element
}

func (v StreamAppView) GetRoot() tui.Renderable { return v.Root }

func (v StreamAppView) GetWatchers() []tui.Watcher { return v.watchers }

func StreamApp(dataCh <-chan string) StreamAppView {
	var view StreamAppView
	var watchers []tui.Watcher

	lineCount := tui.NewState(0)
	elapsed := tui.NewState(0)
	content := tui.NewRef()
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
	)
	__tui_1 := tui.New(
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_2 := tui.New(
		tui.WithText("Streaming DSL Demo - Use arrow keys to scroll, q to quit"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.White)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithFocusable(true),
	)
	content.Set(__tui_3)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Blue)),
		tui.WithBorder(tui.BorderSingle),
		tui.WithHeight(3),
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_5 := tui.New(
		tui.WithText(fmt.Sprintf("Lines: %d | Elapsed: %ds | Press q to exit", lineCount.Get(), elapsed.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.White)),
	)
	__tui_4.AddChild(__tui_5)
	__tui_0.AddChild(__tui_4)

	// Attach watchers (deferred until refs are assigned)
	__tui_0.AddWatcher(tui.OnTimer(time.Second, tickElapsed(elapsed)))
	__tui_0.AddWatcher(tui.Watch(dataCh, addLine(lineCount, content)))

	// State bindings
	__update___tui_5 := func() {
		__tui_5.SetText(fmt.Sprintf("Lines: %d | Elapsed: %ds | Press q to exit", lineCount.Get(), elapsed.Get()))
	}
	lineCount.Bind(func(_ int) { __update___tui_5() })
	elapsed.Bind(func(_ int) { __update___tui_5() })

	view = StreamAppView{
		Root:     __tui_0,
		watchers: watchers,
		Content:  content.El(),
	}
	return view
}
