// Code generated by tui generate. DO NOT EDIT.
// Source: scrolling.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type fileList struct {
	files    []string
	selected *tui.State[int]
	scrollY  *tui.State[int]
	content  *tui.Ref
}

func FileList() *fileList {
	files := []string{
		"main.go", "app.go", "app_loop.go", "app_render.go",
		"buffer.go", "cell.go", "color.go", "component.go",
		"dirty.go", "element.go", "element_options.go",
		"element_render.go", "element_scroll.go", "escape.go",
		"event.go", "focus.go", "key.go", "keymap.go",
		"layout.go", "mount.go", "ref.go", "render.go",
		"state.go", "style.go", "terminal.go", "watcher.go",
	}
	return &fileList{
		files:    files,
		selected: tui.NewState(0),
		scrollY:  tui.NewState(0),
		content:  tui.NewRef(),
	}
}

func (f *fileList) scrollBy(delta int) {
	el := f.content.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := f.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	}
	if newY > maxY {
		newY = maxY
	}
	f.scrollY.Set(newY)
}

func (f *fileList) moveTo(idx int) {
	if idx < 0 {
		idx = len(f.files) - 1
	}
	if idx >= len(f.files) {
		idx = 0
	}
	f.selected.Set(idx)

	// Keep selected item visible by adjusting scroll
	el := f.content.El()
	if el == nil {
		return
	}
	_, vpH := el.ViewportSize()
	y := f.scrollY.Get()
	if idx < y {
		f.scrollY.Set(idx)
	} else if idx >= y+vpH {
		f.scrollY.Set(idx - vpH + 1)
	}
}

func (f *fileList) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnRune('j', func(ke tui.KeyEvent) { f.moveTo(f.selected.Get() + 1) }),
		tui.OnRune('k', func(ke tui.KeyEvent) { f.moveTo(f.selected.Get() - 1) }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { f.moveTo(f.selected.Get() + 1) }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { f.moveTo(f.selected.Get() - 1) }),
		tui.OnKey(tui.KeyPageDown, func(ke tui.KeyEvent) { f.moveTo(f.selected.Get() + 10) }),
		tui.OnKey(tui.KeyPageUp, func(ke tui.KeyEvent) { f.moveTo(f.selected.Get() - 10) }),
		tui.OnKey(tui.KeyHome, func(ke tui.KeyEvent) { f.moveTo(0) }),
		tui.OnKey(tui.KeyEnd, func(ke tui.KeyEvent) { f.moveTo(len(f.files) - 1) }),
	}
}

func (f *fileList) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		f.scrollBy(-3)
		return true
	case tui.MouseWheelDown:
		f.scrollBy(3)
		return true
	}
	return false
}

func (f *fileList) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithText("Files"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollbarStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithScrollbarThumbStyle(tui.NewStyle().Foreground(tui.BrightCyan)),
		tui.WithHeight(12),
		tui.WithScrollOffset(0, f.scrollY.Get()),
	)
	f.content.Set(__tui_2)
	for i, name := range f.files {
		_ = i
		if i == f.selected.Get() {
			__tui_3 := tui.New(
				tui.WithText(fmt.Sprintf(" > %s ", name)),
				tui.WithBackground(tui.NewStyle().Background(tui.BrightBlack)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_2.AddChild(__tui_3)
		} else {
			__tui_4 := tui.New(
				tui.WithText(fmt.Sprintf("   %s", name)),
			)
			__tui_2.AddChild(__tui_4)
		}
	}
	__tui_0.AddChild(__tui_2)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_6 := tui.New(
		tui.WithText("j/k navigate|esc quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_5.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText(fmt.Sprintf("%d/%d", f.selected.Get()+1, len(f.files))),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_5.AddChild(__tui_7)
	__tui_0.AddChild(__tui_5)

	return __tui_0
}

func (f *fileList) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*fileList)
	if !ok {
		return
	}
	f.files = f.files
}

var _ tui.PropsUpdater = (*fileList)(nil)

func (f *fileList) BindApp(app *tui.App) {
	if f.selected != nil {
		f.selected.BindApp(app)
	}
	if f.scrollY != nil {
		f.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*fileList)(nil)
