// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

type counterApp struct {
	count   *tui.State[int]
	elapsed *tui.State[int]
	display *tui.Ref
}

func Counter() *counterApp {
	return &counterApp{
		count:   tui.NewState(0),
		elapsed: tui.NewState(0),
		display: tui.NewRef(),
	}
}

func (c *counterApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('+', func(ke tui.KeyEvent) {
			c.count.Update(func(v int) int { return v + 1 })
		}),
		tui.OnRune('-', func(ke tui.KeyEvent) {
			c.count.Update(func(v int) int { return v - 1 })
		}),
		tui.OnRune('r', func(ke tui.KeyEvent) { c.count.Set(0) }),
		tui.OnRune('q', func(ke tui.KeyEvent) { ke.App().Stop() }),
	}
}

func (c *counterApp) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.OnTimer(time.Second, func() {
			c.elapsed.Update(func(v int) int { return v + 1 })
		}),
	}
}

func formatTime(seconds int) string {
	return fmt.Sprintf("%d:%02d", seconds/60, seconds%60)
}

type BadgeView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v BadgeView) GetRoot() tui.Renderable { return v.Root }

func (v BadgeView) GetWatchers() []tui.Watcher { return v.watchers }

func (v BadgeView) Render(app *tui.App) *tui.Element { return v.Root }

func (v BadgeView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = BadgeView{}

func Badge(label string, value string, color string) BadgeView {
	var view BadgeView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText(label),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(value),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	view = BadgeView{
		Root:     __tui_0,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}

type CardView struct {
	Root     *tui.Element
	watchers []tui.Watcher
	bindApp  func(*tui.App)
}

func (v CardView) GetRoot() tui.Renderable { return v.Root }

func (v CardView) GetWatchers() []tui.Watcher { return v.watchers }

func (v CardView) Render(app *tui.App) *tui.Element { return v.Root }

func (v CardView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

var _ tui.AppBinder = CardView{}

func Card(title string, children []*tui.Element) CardView {
	var view CardView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_1 := tui.New(
		tui.WithText(title),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	for _, __child := range children {
		__tui_0.AddChild(__child)
	}

	__bindApp := func(app *tui.App) {
	}

	view = CardView{
		Root:     __tui_0,
		watchers: watchers,
		bindApp:  __bindApp,
	}
	return view
}

func (c *counterApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_2 := tui.New(
		tui.WithText("Counter"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := app.Mount(c, 0, func() tui.Component {
		return Badge("uptime:", formatTime(c.elapsed.Get()), "text-yellow")
	})
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_6_children := []*tui.Element{}
	__tui_7 := tui.New(
		tui.WithText(fmt.Sprintf("%d", c.count.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	c.display.Set(__tui_7)
	__tui_6_children = append(__tui_6_children, __tui_7)
	__tui_6 := app.Mount(c, 1, func() tui.Component {
		return Card("Count", __tui_6_children)
	})
	__tui_5.AddChild(__tui_6)
	__tui_8_children := []*tui.Element{}
	if c.count.Get() > 0 {
		__tui_9 := tui.New(
			tui.WithText("Positive"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
		)
		__tui_8_children = append(__tui_8_children, __tui_9)
	} else if c.count.Get() < 0 {
		__tui_10 := tui.New(
			tui.WithText("Negative"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_8_children = append(__tui_8_children, __tui_10)
	} else {
		__tui_11 := tui.New(
			tui.WithText("Zero"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue).Bold()),
		)
		__tui_8_children = append(__tui_8_children, __tui_11)
	}
	__tui_8 := app.Mount(c, 2, func() tui.Component {
		return Card("Status", __tui_8_children)
	})
	__tui_5.AddChild(__tui_8)
	__tui_0.AddChild(__tui_5)
	__tui_12 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_13 := tui.New(
		tui.WithText("+/-count·r reset·q quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_12.AddChild(__tui_13)
	__tui_0.AddChild(__tui_12)

	return __tui_0
}

func (c *counterApp) BindApp(app *tui.App) {
	if c.count != nil {
		c.count.BindApp(app)
	}
	if c.elapsed != nil {
		c.elapsed.BindApp(app)
	}
}

var _ tui.AppBinder = (*counterApp)(nil)
