// Code generated by tui generate. DO NOT EDIT.
// Source: focus.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type focusApp struct {
	focused *tui.State[string]
}

func Focus() *focusApp {
	return &focusApp{
		focused: tui.NewState("(none)"),
	}
}

func (f *focusApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
	}
}

func onFocusBox(name string, focused *tui.State[string]) func(*tui.Element) {
	return func(el *tui.Element) {
		focused.Set(name)
		el.SetBorder(tui.BorderDouble)
	}
}

func onBlurBox(focused *tui.State[string]) func(*tui.Element) {
	return func(el *tui.Element) {
		focused.Set("(none)")
		el.SetBorder(tui.BorderSingle)
	}
}

func (f *focusApp) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(2),
		tui.WithPadding(2),
	)
	__tui_1 := tui.New(
		tui.WithText("Focus Navigation"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_4 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(2),
		tui.WithWidth(15),
		tui.WithHeight(5),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFocusable(true),
		tui.WithOnFocus(onFocusBox("Box A", f.focused)),
		tui.WithOnBlur(onBlurBox(f.focused)),
	)
	__tui_5 := tui.New(
		tui.WithText("Box A"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
	)
	__tui_4.AddChild(__tui_5)
	__tui_3.AddChild(__tui_4)
	__tui_6 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(2),
		tui.WithWidth(15),
		tui.WithHeight(5),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFocusable(true),
		tui.WithOnFocus(onFocusBox("Box B", f.focused)),
		tui.WithOnBlur(onBlurBox(f.focused)),
	)
	__tui_7 := tui.New(
		tui.WithText("Box B"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
	)
	__tui_6.AddChild(__tui_7)
	__tui_3.AddChild(__tui_6)
	__tui_8 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(2),
		tui.WithWidth(15),
		tui.WithHeight(5),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFocusable(true),
		tui.WithOnFocus(onFocusBox("Box C", f.focused)),
		tui.WithOnBlur(onBlurBox(f.focused)),
	)
	__tui_9 := tui.New(
		tui.WithText("Box C"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue)),
	)
	__tui_8.AddChild(__tui_9)
	__tui_3.AddChild(__tui_8)
	__tui_0.AddChild(__tui_3)
	__tui_10 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_11 := tui.New(
		tui.WithText("Focused:"),
	)
	__tui_10.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText(f.focused.Get()),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Yellow)),
	)
	__tui_10.AddChild(__tui_12)
	__tui_0.AddChild(__tui_10)
	__tui_13 := tui.New(
		tui.WithText("Press Tab/Shift+Tab to navigate, q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_13)

	return __tui_0
}
