// Code generated by tui generate. DO NOT EDIT.
// Source: keyboard.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type keyboardApp struct {
	lastKey  *tui.State[string]
	keyCount *tui.State[int]
}

func Keyboard() *keyboardApp {
	return &keyboardApp{
		lastKey:  tui.NewState("(none)"),
		keyCount: tui.NewState(0),
	}
}

func (k *keyboardApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnRunes(func(ke tui.KeyEvent) {
			k.keyCount.Set(k.keyCount.Get() + 1)
			k.lastKey.Set(fmt.Sprintf("'%c' (rune)", ke.Rune))
		}),
		tui.OnKey(tui.KeyEnter, func(ke tui.KeyEvent) { k.recordSpecial("Enter") }),
		tui.OnKey(tui.KeyBackspace, func(ke tui.KeyEvent) { k.recordSpecial("Backspace") }),
		tui.OnKey(tui.KeyTab, func(ke tui.KeyEvent) { k.recordSpecial("Tab") }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) { k.recordSpecial("Up Arrow") }),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) { k.recordSpecial("Down Arrow") }),
		tui.OnKey(tui.KeyLeft, func(ke tui.KeyEvent) { k.recordSpecial("Left Arrow") }),
		tui.OnKey(tui.KeyRight, func(ke tui.KeyEvent) { k.recordSpecial("Right Arrow") }),
		tui.OnKey(tui.KeyHome, func(ke tui.KeyEvent) { k.recordSpecial("Home") }),
		tui.OnKey(tui.KeyEnd, func(ke tui.KeyEvent) { k.recordSpecial("End") }),
		tui.OnKey(tui.KeyPageUp, func(ke tui.KeyEvent) { k.recordSpecial("Page Up") }),
		tui.OnKey(tui.KeyPageDown, func(ke tui.KeyEvent) { k.recordSpecial("Page Down") }),
		tui.OnKey(tui.KeyDelete, func(ke tui.KeyEvent) { k.recordSpecial("Delete") }),
		tui.OnKey(tui.KeyInsert, func(ke tui.KeyEvent) { k.recordSpecial("Insert") }),
	}
}

func (k *keyboardApp) recordSpecial(name string) {
	k.keyCount.Set(k.keyCount.Get() + 1)
	k.lastKey.Set(name)
}

func (k *keyboardApp) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithBorder(tui.BorderRounded),
	)
	__tui_1 := tui.New(
		tui.WithText("Keyboard Events"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_4 := tui.New(
		tui.WithText("Last key pressed:"),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(k.lastKey.Get()),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Green)),
	)
	__tui_3.AddChild(__tui_5)
	__tui_0.AddChild(__tui_3)
	__tui_6 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_7 := tui.New(
		tui.WithText("Total keys pressed:"),
	)
	__tui_6.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText(fmt.Sprintf("%d", k.keyCount.Get())),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Blue)),
	)
	__tui_6.AddChild(__tui_8)
	__tui_0.AddChild(__tui_6)
	__tui_9 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText("Press any key to see it displayed, q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)

	return __tui_0
}
