// Code generated by tui generate. DO NOT EDIT.
// Source: keyboard.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

func handleKey(lastKey *tui.State[string], keyCount *tui.State[int]) func(*tui.Element, tui.KeyEvent) {
	return func(el *tui.Element, e tui.KeyEvent) {
		keyCount.Set(keyCount.Get() + 1)

		if e.Rune != 0 {
			lastKey.Set(fmt.Sprintf("'%c' (rune)", e.Rune))
		} else {
			lastKey.Set(keyName(e.Key))
		}
	}
}

func keyName(key tui.Key) string {
	switch key {
	case tui.KeyEnter:
		return "Enter"
	case tui.KeyBackspace:
		return "Backspace"
	case tui.KeyTab:
		return "Tab"
	case tui.KeyEscape:
		return "Escape"
	case tui.KeyUp:
		return "Up Arrow"
	case tui.KeyDown:
		return "Down Arrow"
	case tui.KeyLeft:
		return "Left Arrow"
	case tui.KeyRight:
		return "Right Arrow"
	case tui.KeyHome:
		return "Home"
	case tui.KeyEnd:
		return "End"
	case tui.KeyPageUp:
		return "Page Up"
	case tui.KeyPageDown:
		return "Page Down"
	case tui.KeyDelete:
		return "Delete"
	case tui.KeyInsert:
		return "Insert"
	default:
		return fmt.Sprintf("Key(%d)", key)
	}
}

type KeyboardView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v KeyboardView) GetRoot() tui.Renderable { return v.Root }

func (v KeyboardView) GetWatchers() []tui.Watcher { return v.watchers }

func Keyboard() KeyboardView {
	var view KeyboardView
	var watchers []tui.Watcher

	lastKey := tui.NewState("(none)")
	keyCount := tui.NewState(0)
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(2),
		tui.WithBorder(tui.BorderRounded),
		tui.WithOnKeyPress(handleKey(lastKey, keyCount)),
	)
	__tui_1 := tui.New(
		tui.WithText("Keyboard Events"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_4 := tui.New(
		tui.WithText("Last key pressed:"),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(lastKey.Get()),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Green)),
	)
	__tui_3.AddChild(__tui_5)
	__tui_0.AddChild(__tui_3)
	__tui_6 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(2),
	)
	__tui_7 := tui.New(
		tui.WithText("Total keys pressed:"),
	)
	__tui_6.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText(fmt.Sprintf("%d", keyCount.Get())),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Blue)),
	)
	__tui_6.AddChild(__tui_8)
	__tui_0.AddChild(__tui_6)
	__tui_9 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText("Press any key to see it displayed, q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)

	// State bindings
	lastKey.Bind(func(_ string) {
		__tui_5.SetText(lastKey.Get())
	})
	keyCount.Bind(func(_ int) {
		__tui_8.SetText(fmt.Sprintf("%d", keyCount.Get()))
	})

	view = KeyboardView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
