// Code generated by tui generate. DO NOT EDIT.
// Source: scrollable.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

func handleScrollKeys(el *tui.Element, e tui.KeyEvent) {
	switch e.Rune {
	case 'j':
		el.ScrollBy(0, 1)
		return
	case 'k':
		el.ScrollBy(0, -1)
		return
	}
	switch e.Key {
	case tui.KeyDown:
		el.ScrollBy(0, 1)
		return
	case tui.KeyUp:
		el.ScrollBy(0, -1)
		return
	}
}

func handleMouseScroll(el *tui.Element, e tui.Event) bool {
	if mouse, ok := e.(tui.MouseEvent); ok {
		switch mouse.Button {
		case tui.MouseWheelUp:
			el.ScrollBy(0, -1)
			return true
		case tui.MouseWheelDown:
			el.ScrollBy(0, 1)
			return true
		}
	}
	return false
}

type ScrollableView struct {
	Root     *tui.Element
	watchers []tui.Watcher
}

func (v ScrollableView) GetRoot() tui.Renderable { return v.Root }

func (v ScrollableView) GetWatchers() []tui.Watcher { return v.watchers }

func Scrollable(items []string) ScrollableView {
	var view ScrollableView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(1),
		tui.WithHeightPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithText("Scrollable Content"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithFocusable(true),
		tui.WithOnEvent(handleMouseScroll),
		tui.WithOnKeyPress(handleScrollKeys),
	)
	for i, item := range items {
		_ = i
		__tui_4 := tui.New(
			tui.WithText(fmt.Sprintf("%02d. %s", i+1, item)),
		)
		__tui_3.AddChild(__tui_4)
	}
	__tui_0.AddChild(__tui_3)
	__tui_5 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithGap(1),
		tui.WithDirection(tui.Row),
		tui.WithDirection(tui.Row),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_6 := tui.New(
		tui.WithText("Use arrow keys or j"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_5.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("k to scroll"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_5.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("q to quit"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_5.AddChild(__tui_8)
	__tui_0.AddChild(__tui_5)

	view = ScrollableView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
