// Code generated by tui generate. DO NOT EDIT.
// Source: scrollable.gsx

package main

import (
	"fmt"

	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func handleScrollKeys(content *element.Element) func(tui.KeyEvent) {
	return func(e tui.KeyEvent) {
		switch e.Rune {
		case 'j':
			content.ScrollBy(0, 1)
			return
		case 'k':
			content.ScrollBy(0, -1)
			return
		}
		switch e.Key {
		case tui.KeyDown:
			content.ScrollBy(0, 1)
			return
		case tui.KeyUp:
			content.ScrollBy(0, -1)
			return
		}
	}
}

func handleMouseScroll(content *element.Element) func(tui.Event) bool {
	return func(e tui.Event) bool {
		if mouse, ok := e.(tui.MouseEvent); ok {
			switch mouse.Button {
			case tui.MouseWheelUp:
				content.ScrollBy(0, -1)
				return true
			case tui.MouseWheelDown:
				content.ScrollBy(0, 1)
				return true
			}
		}
		return false
	}
}

type ScrollableView struct {
	Root     *element.Element
	watchers []tui.Watcher
	Content  *element.Element
}

func (v ScrollableView) GetRoot() tui.Renderable { return v.Root }

func (v ScrollableView) GetWatchers() []tui.Watcher { return v.watchers }

func Scrollable(items []string) ScrollableView {
	var view ScrollableView
	var watchers []tui.Watcher

	var Content *element.Element

	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(1),
		element.WithHeightPercent(100.00),
	)
	__tui_1 := element.New(
		element.WithText("Scrollable Content"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := element.New(
		element.WithHR(),
		element.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	Content = element.New(
		element.WithDirection(layout.Column),
		element.WithFlexGrow(1),
		element.WithScrollable(element.ScrollVertical),
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
		element.WithFocusable(true),
	)
	for i, item := range items {
		_ = i
		__tui_3 := element.New(
			element.WithText(fmt.Sprintf("%02d. %s", i+1, item)),
		)
		Content.AddChild(__tui_3)
	}
	__tui_0.AddChild(Content)
	__tui_4 := element.New(
		element.WithWidthPercent(100.00),
		element.WithGap(1),
		element.WithDirection(layout.Row),
		element.WithDirection(layout.Row),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_5 := element.New(
		element.WithText("Use arrow keys or j"),
		element.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_4.AddChild(__tui_5)
	__tui_6 := element.New(
		element.WithText("k to scroll"),
		element.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_4.AddChild(__tui_6)
	__tui_7 := element.New(
		element.WithText("q to quit"),
		element.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_4.AddChild(__tui_7)
	__tui_0.AddChild(__tui_4)

	// Attach handlers (deferred until refs are assigned)
	Content.SetOnEvent(handleMouseScroll(Content))
	Content.SetOnKeyPress(handleScrollKeys(Content))

	view = ScrollableView{
		Root:     __tui_0,
		watchers: watchers,
		Content:  Content,
	}
	return view
}
