// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type counter struct {
	count *tui.State[int]
}

func NewCounter() *counter {
	return &counter{
		count: tui.NewState(0),
	}
}

func (c *counter) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('+'), func(ke tui.KeyEvent) {
			c.count.Update(func(v int) int { return v + 1 })
		}),
		tui.On(tui.Rune('-'), func(ke tui.KeyEvent) {
			c.count.Update(func(v int) int { return v - 1 })
		}),
	}
}

func (c *counter) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_1 := tui.New(
		tui.WithText(fmt.Sprintf("Count: %d", c.count.Get())),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("Press + / - to change, Esc to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)

	return __tui_0
}

func (c *counter) BindApp(app *tui.App) {
	if c.count != nil {
		c.count.BindApp(app)
	}
}

var _ tui.AppBinder = (*counter)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*counter)(nil)
)
