// Code generated by tui generate. DO NOT EDIT.
// Source: simple.gsx

package testdata

import (
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func Header(title string) *element.Element {
	__tui_0 := element.New(
		element.WithBorder(tui.BorderSingle),
		element.WithPadding(1),
	)
	__tui_1 := element.New(
		element.WithText(title),
	)
	__tui_0.AddChild(__tui_1)
	return __tui_0
}

func Footer() *element.Element {
	__tui_0 := element.New(
		element.WithPadding(1),
	)
	__tui_1 := element.New(
		element.WithText("Footer content"),
	)
	__tui_0.AddChild(__tui_1)
	return __tui_0
}
