// Code generated by tui generate. DO NOT EDIT.
// Source: textarea.gsx

package testdata

import (
	tui "github.com/grindlemire/go-tui"
)

type myForm struct {
	app *tui.App
}

func MyForm() *myForm {
	return &myForm{}
}

func (c *myForm) handleSubmit(text string) {}

func (c *myForm) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_1 := app.MountPersistent(c, 0, func() tui.Component {
		return tui.NewTextArea(
			tui.WithTextAreaPlaceholder("Enter text..."),
			tui.WithTextAreaWidth(50),
			tui.WithTextAreaBorder(tui.BorderRounded),
			tui.WithTextAreaOnSubmit(c.handleSubmit),
		)
	})
	__tui_0.AddChild(__tui_1)

	return __tui_0
}

func (c *myForm) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*myForm)
	if !ok {
		return
	}
	c.app = f.app
}

var _ tui.PropsUpdater = (*myForm)(nil)

func (c *myForm) BindApp(app *tui.App) {
	c.app = app
}

var _ tui.AppBinder = (*myForm)(nil)
