// Code generated by tui generate. DO NOT EDIT.
// Source: conditionals.gsx

package main

import (
	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

type ConditionalsView struct {
	Root     *element.Element
	watchers []tui.Watcher
}

func (v ConditionalsView) GetRoot() tui.Renderable { return v.Root }

func (v ConditionalsView) GetWatchers() []tui.Watcher { return v.watchers }

func Conditionals(enabled bool) ConditionalsView {
	var view ConditionalsView
	var watchers []tui.Watcher

	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(2),
		element.WithBorder(tui.BorderRounded),
	)
	__tui_1 := element.New(
		element.WithText("Conditional Rendering"),
		element.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := element.New(
		element.WithHR(),
		element.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := element.New(
		element.WithDirection(layout.Row),
		element.WithGap(1),
	)
	__tui_4 := element.New(
		element.WithText("Status:"),
	)
	__tui_3.AddChild(__tui_4)
	if enabled {
		__tui_5 := element.New(
			element.WithText("Enabled"),
			element.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
		)
		__tui_3.AddChild(__tui_5)
	} else {
		__tui_6 := element.New(
			element.WithText("Disabled"),
			element.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_3.AddChild(__tui_6)
	}
	__tui_0.AddChild(__tui_3)
	if enabled {
		__tui_7 := element.New(
			element.WithBorder(tui.BorderSingle),
			element.WithPadding(1),
			element.WithBackground(tui.NewStyle().Background(tui.Green)),
		)
		__tui_8 := element.New(
			element.WithText("This content only shows when enabled!"),
		)
		__tui_7.AddChild(__tui_8)
		__tui_0.AddChild(__tui_7)
	}
	__tui_9 := element.New(
		element.WithWidth(0),
		element.WithHeight(1),
	)
	__tui_0.AddChild(__tui_9)
	__tui_10 := element.New(
		element.WithText("Press t to toggle, q to quit"),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_10)

	view = ConditionalsView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
