// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type counter struct {
	count        *tui.State[int]
	events       *Events[string]
	decrementBtn *tui.Ref
	incrementBtn *tui.Ref
	resetBtn     *tui.Ref
}

func Counter(events *Events[string]) *counter {
	return &counter{
		count:        tui.NewState(0),
		events:       events,
		decrementBtn: tui.NewRef(),
		incrementBtn: tui.NewRef(),
		resetBtn:     tui.NewRef(),
	}
}

func (c *counter) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('+', func(ke tui.KeyEvent) { c.increment() }),
		tui.OnRune('=', func(ke tui.KeyEvent) { c.increment() }),
		tui.OnRune('-', func(ke tui.KeyEvent) { c.decrement() }),
		tui.OnRune('0', func(ke tui.KeyEvent) { c.reset() }),
	}
}

func (c *counter) HandleMouse(me tui.MouseEvent) bool {
	return tui.HandleClicks(me,
		tui.Click(c.decrementBtn, c.decrement),
		tui.Click(c.incrementBtn, c.increment),
		tui.Click(c.resetBtn, c.reset),
	)
}

func (c *counter) increment() {
	c.count.Set(c.count.Get() + 1)
	c.events.Emit("increment")
}

func (c *counter) decrement() {
	c.count.Set(c.count.Get() - 1)
	c.events.Emit("decrement")
}

func (c *counter) reset() {
	c.count.Set(0)
	c.events.Emit("reset")
}

func (c *counter) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_1 := tui.New(
		tui.WithText("Counter"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_3 := tui.New(
		tui.WithText("Count:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(fmt.Sprintf("%d", c.count.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_4)
	__tui_0.AddChild(__tui_2)
	__tui_5 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_6 := tui.New()
	c.decrementBtn.Set(__tui_6)
	__tui_7 := tui.New(tui.WithText(" - "))
	__tui_6.AddChild(__tui_7)
	__tui_5.AddChild(__tui_6)
	__tui_8 := tui.New()
	c.incrementBtn.Set(__tui_8)
	__tui_9 := tui.New(tui.WithText(" + "))
	__tui_8.AddChild(__tui_9)
	__tui_5.AddChild(__tui_8)
	__tui_10 := tui.New()
	c.resetBtn.Set(__tui_10)
	__tui_11 := tui.New(tui.WithText(" 0 "))
	__tui_10.AddChild(__tui_11)
	__tui_5.AddChild(__tui_10)
	__tui_0.AddChild(__tui_5)
	if c.count.Get() > 0 {
		__tui_12 := tui.New(
			tui.WithText("Positive"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
		)
		__tui_0.AddChild(__tui_12)
	} else if c.count.Get() < 0 {
		__tui_13 := tui.New(
			tui.WithText("Negative"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_0.AddChild(__tui_13)
	} else {
		__tui_14 := tui.New(
			tui.WithText("Zero"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue).Bold()),
		)
		__tui_0.AddChild(__tui_14)
	}
	__tui_15 := tui.New(
		tui.WithFlexGrow(1.0),
	)
	__tui_0.AddChild(__tui_15)
	__tui_16 := tui.New(
		tui.WithText("click btns or +/-/0"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_16)

	return __tui_0
}
