// Code generated by tui generate. DO NOT EDIT.
// Source: counter.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

type counter struct {
	count        *tui.State[int]
	pending      *tui.State[bool]
	events       *tui.Events[string]
	delayCh      chan int
	decrementBtn *tui.Ref
	incrementBtn *tui.Ref
	resetBtn     *tui.Ref
}

var (
	_ tui.Component       = (*counter)(nil)
	_ tui.WatcherProvider = (*counter)(nil)
	_ tui.MouseListener   = (*counter)(nil)
	_ tui.KeyListener     = (*counter)(nil)
)

func Counter(events *tui.Events[string]) *counter {
	return &counter{
		count:        tui.NewState(0),
		pending:      tui.NewState(false),
		events:       events,
		delayCh:      make(chan int),
		decrementBtn: tui.NewRef(),
		incrementBtn: tui.NewRef(),
		resetBtn:     tui.NewRef(),
	}
}

func (c *counter) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('+', func(ke tui.KeyEvent) { c.increment() }),
		tui.OnRune('=', func(ke tui.KeyEvent) { c.increment() }),
		tui.OnRune('-', func(ke tui.KeyEvent) { c.decrement() }),
		tui.OnRune('0', func(ke tui.KeyEvent) { c.reset() }),
		tui.OnRune('d', func(ke tui.KeyEvent) { c.delayedIncrement() }),
	}
}

func (c *counter) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.Watch(c.delayCh, func(delta int) {
			c.count.Set(c.count.Get() + delta)
			c.pending.Set(false)
			c.events.Emit("delayed +1")
		}),
	}
}

func (c *counter) delayedIncrement() {
	if c.pending.Get() {
		return // Already pending
	}
	c.pending.Set(true)
	c.events.Emit("delay started")
	go func() {
		time.Sleep(1 * time.Second)
		c.delayCh <- 1
	}()
}

func (c *counter) HandleMouse(me tui.MouseEvent) bool {
	return tui.HandleClicks(me,
		tui.Click(c.decrementBtn, c.decrement),
		tui.Click(c.incrementBtn, c.increment),
		tui.Click(c.resetBtn, c.reset),
	)
}

func (c *counter) increment() {
	c.count.Set(c.count.Get() + 1)
	c.events.Emit("increment")
}

func (c *counter) decrement() {
	c.count.Set(c.count.Get() - 1)
	c.events.Emit("decrement")
}

func (c *counter) reset() {
	c.count.Set(0)
	c.events.Emit("reset")
}

func (c *counter) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithWidthPercent(50.00),
	)
	__tui_1 := tui.New(
		tui.WithText("Counter"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Blue).WithDirection(tui.GradientHorizontal)),
		tui.WithTextAlign(tui.TextAlignCenter),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_3 := tui.New(
		tui.WithText("Count:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(fmt.Sprintf("%d", c.count.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_2.AddChild(__tui_4)
	__tui_0.AddChild(__tui_2)
	__tui_5 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithJustify(tui.JustifyCenter),
	)
	__tui_6 := tui.New()
	c.decrementBtn.Set(__tui_6)
	__tui_7 := tui.New(tui.WithText(" - "))
	__tui_6.AddChild(__tui_7)
	__tui_5.AddChild(__tui_6)
	__tui_8 := tui.New()
	c.incrementBtn.Set(__tui_8)
	__tui_9 := tui.New(tui.WithText(" + "))
	__tui_8.AddChild(__tui_9)
	__tui_5.AddChild(__tui_8)
	__tui_10 := tui.New()
	c.resetBtn.Set(__tui_10)
	__tui_11 := tui.New(tui.WithText(" 0 "))
	__tui_10.AddChild(__tui_11)
	__tui_5.AddChild(__tui_10)
	__tui_0.AddChild(__tui_5)
	if c.pending.Get() {
		__tui_12 := tui.New(
			tui.WithText("Pending..."),
			tui.WithTextAlign(tui.TextAlignCenter),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_0.AddChild(__tui_12)
	} else if c.count.Get() > 0 {
		__tui_13 := tui.New(
			tui.WithText("Positive"),
			tui.WithTextAlign(tui.TextAlignCenter),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
		)
		__tui_0.AddChild(__tui_13)
	} else if c.count.Get() < 0 {
		__tui_14 := tui.New(
			tui.WithText("Negative"),
			tui.WithTextAlign(tui.TextAlignCenter),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_0.AddChild(__tui_14)
	} else {
		__tui_15 := tui.New(
			tui.WithText("Zero"),
			tui.WithTextAlign(tui.TextAlignCenter),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue).Bold()),
		)
		__tui_0.AddChild(__tui_15)
	}

	return __tui_0
}
