// Code generated by tui generate. DO NOT EDIT.
// Source: interactive.gsx

package main

import (
	"fmt"

	"github.com/grindlemire/go-tui/pkg/layout"
	"github.com/grindlemire/go-tui/pkg/tui"
	"github.com/grindlemire/go-tui/pkg/tui/element"
)

func increment(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() + 1)
	}
}

func decrement(count *tui.State[int]) func() {
	return func() {
		count.Set(count.Get() - 1)
	}
}

func reset(count *tui.State[int]) func() {
	return func() {
		count.Set(0)
	}
}

func keyPress(count *tui.State[int]) func(tui.KeyEvent) {
	return func(e tui.KeyEvent) {
		if e.Rune == '-' {
			count.Set(count.Get() - 1)
		} else if e.Rune == '+' {
			count.Set(count.Get() + 1)
		}
	}
}

type CounterView struct {
	Root     *element.Element
	watchers []tui.Watcher
}

func (v CounterView) GetRoot() tui.Renderable { return v.Root }

func (v CounterView) GetWatchers() []tui.Watcher { return v.watchers }

func Counter() CounterView {
	var view CounterView
	var watchers []tui.Watcher

	count := tui.NewState(0)
	__tui_0 := element.New(
		element.WithDirection(layout.Column),
		element.WithGap(1),
		element.WithPadding(2),
		element.WithBorder(tui.BorderRounded),
	)
	__tui_1 := element.New(
		element.WithText("Interactive Counter"),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := element.New(
		element.WithHR(),
		element.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := element.New(
		element.WithDirection(layout.Row),
		element.WithGap(2),
		element.WithAlign(layout.AlignCenter),
	)
	__tui_4 := element.New(
		element.WithText("Count"),
	)
	__tui_3.AddChild(__tui_4)
	__tui_5 := element.New(
		element.WithText(fmt.Sprintf("%d", count.Get())),
		element.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Blue)),
	)
	__tui_3.AddChild(__tui_5)
	__tui_0.AddChild(__tui_3)
	__tui_6 := element.New(
		element.WithDirection(layout.Row),
		element.WithGap(1),
	)
	__tui_7 := element.New()
	__tui_8 := element.New(element.WithText(" - "))
	__tui_7.AddChild(__tui_8)
	__tui_6.AddChild(__tui_7)
	__tui_9 := element.New()
	__tui_10 := element.New(element.WithText(" + "))
	__tui_9.AddChild(__tui_10)
	__tui_6.AddChild(__tui_9)
	__tui_11 := element.New()
	__tui_12 := element.New(element.WithText(" Reset "))
	__tui_11.AddChild(__tui_12)
	__tui_6.AddChild(__tui_11)
	__tui_0.AddChild(__tui_6)
	__tui_13 := element.New(
		element.WithText("Click buttons or press q to quit"),
		element.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_13)

	// Attach handlers (deferred until refs are assigned)
	__tui_7.SetOnKeyPress(keyPress(count))
	__tui_7.SetOnClick(decrement(count))
	__tui_9.SetOnKeyPress(keyPress(count))
	__tui_9.SetOnClick(increment(count))
	__tui_11.SetOnClick(reset(count))

	// State bindings
	count.Bind(func(_ int) {
		__tui_5.SetText(fmt.Sprintf("%d", count.Get()))
	})

	view = CounterView{
		Root:     __tui_0,
		watchers: watchers,
	}
	return view
}
