// Code generated by tui generate. DO NOT EDIT.
// Source: interactive.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type interactiveApp struct {
	events *Events[string]
}

func Interactive() *interactiveApp {
	return &interactiveApp{
		events: NewEvents[string](),
	}
}

func (a *interactiveApp) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnRune('q', func(ke tui.KeyEvent) { tui.Stop() }),
		tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) { tui.Stop() }),
	}
}

func (a *interactiveApp) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
	)
	__tui_2 := tui.New(
		tui.WithText("Interactive Elements"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("[q] quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_5 := tui.Mount(a, 0, func() tui.Component {
		return Counter(a.events)
	})
	__tui_4.AddChild(__tui_5)
	__tui_6 := tui.Mount(a, 1, func() tui.Component {
		return Timer(a.events)
	})
	__tui_4.AddChild(__tui_6)
	__tui_0.AddChild(__tui_4)
	__tui_7 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_8 := tui.Mount(a, 2, func() tui.Component {
		return Toggles(a.events)
	})
	__tui_7.AddChild(__tui_8)
	__tui_9 := tui.Mount(a, 3, func() tui.Component {
		return EventInspector(a.events)
	})
	__tui_7.AddChild(__tui_9)
	__tui_0.AddChild(__tui_7)

	return __tui_0
}
