// Code generated by tui generate. DO NOT EDIT.
// Source: timer.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

type timer struct {
	elapsed *tui.State[int]
	running *tui.State[bool]
	events  *Events[string]
}

func Timer(events *Events[string]) *timer {
	return &timer{
		elapsed: tui.NewState(0),
		running: tui.NewState(true),
		events:  events,
	}
}

func (t *timer) OnMount(r *Registrar) {
	// Keyboard
	r.OnRune(' ', t.toggleRunning)
	r.OnRune('r', t.resetTimer)

	// Timer - runs every second
	r.Every(time.Second, t.tick)
}

func (t *timer) toggleRunning() {
	t.running.Set(!t.running.Get())
	t.events.Emit("timer toggle")
}

func (t *timer) resetTimer() {
	t.elapsed.Set(0)
	t.events.Emit("timer reset")
}

func (t *timer) tick() {
	if t.running.Get() {
		t.elapsed.Set(t.elapsed.Get() + 1)
	}
}

func formatTime(seconds int) string {
	m := seconds / 60
	s := seconds - (m * 60)
	return fmt.Sprintf("%02d:%02d", m, s)
}

func (t *timer) Render() *tui.Element {
	__tui_0 := tui.New(
		tui.WithBorder(tui.BorderSingle),
		tui.WithPadding(1),
		tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_1 := tui.New(
		tui.WithText("Timer"),
		tui.WithTextGradient(tui.NewGradient(tui.Blue, tui.Cyan).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithAlign(tui.AlignCenter),
	)
	__tui_3 := tui.New(
		tui.WithText("Elapsed:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(formatTime(t.elapsed.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Blue).Bold()),
	)
	__tui_2.AddChild(__tui_4)
	__tui_0.AddChild(__tui_2)
	if t.running.Get() {
		__tui_5 := tui.New(
			tui.WithText("Running"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
		)
		__tui_0.AddChild(__tui_5)
	} else {
		__tui_6 := tui.New(
			tui.WithText("Stopped"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_0.AddChild(__tui_6)
	}
	__tui_7 := tui.New(
		tui.WithText("[space] toggle [r] reset"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_7)

	return __tui_0
}
